/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;
import static com.formance.formance_sdk.operations.Operations.RequestlessOperation;

import com.formance.formance_sdk.models.ledger.V2ExporterConfiguration2;
import com.formance.formance_sdk.models.operations.V2AddMetadataOnTransactionRequest;
import com.formance.formance_sdk.models.operations.V2AddMetadataOnTransactionRequestBuilder;
import com.formance.formance_sdk.models.operations.V2AddMetadataOnTransactionResponse;
import com.formance.formance_sdk.models.operations.V2AddMetadataToAccountRequest;
import com.formance.formance_sdk.models.operations.V2AddMetadataToAccountRequestBuilder;
import com.formance.formance_sdk.models.operations.V2AddMetadataToAccountResponse;
import com.formance.formance_sdk.models.operations.V2CountAccountsRequest;
import com.formance.formance_sdk.models.operations.V2CountAccountsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2CountAccountsResponse;
import com.formance.formance_sdk.models.operations.V2CountTransactionsRequest;
import com.formance.formance_sdk.models.operations.V2CountTransactionsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2CountTransactionsResponse;
import com.formance.formance_sdk.models.operations.V2CreateBulkRequest;
import com.formance.formance_sdk.models.operations.V2CreateBulkRequestBuilder;
import com.formance.formance_sdk.models.operations.V2CreateBulkResponse;
import com.formance.formance_sdk.models.operations.V2CreateExporterRequestBuilder;
import com.formance.formance_sdk.models.operations.V2CreateExporterResponse;
import com.formance.formance_sdk.models.operations.V2CreateLedgerRequest;
import com.formance.formance_sdk.models.operations.V2CreateLedgerRequestBuilder;
import com.formance.formance_sdk.models.operations.V2CreateLedgerResponse;
import com.formance.formance_sdk.models.operations.V2CreatePipelineRequest;
import com.formance.formance_sdk.models.operations.V2CreatePipelineRequestBuilder;
import com.formance.formance_sdk.models.operations.V2CreatePipelineResponse;
import com.formance.formance_sdk.models.operations.V2CreateTransactionRequest;
import com.formance.formance_sdk.models.operations.V2CreateTransactionRequestBuilder;
import com.formance.formance_sdk.models.operations.V2CreateTransactionResponse;
import com.formance.formance_sdk.models.operations.V2DeleteAccountMetadataRequest;
import com.formance.formance_sdk.models.operations.V2DeleteAccountMetadataRequestBuilder;
import com.formance.formance_sdk.models.operations.V2DeleteAccountMetadataResponse;
import com.formance.formance_sdk.models.operations.V2DeleteBucketRequest;
import com.formance.formance_sdk.models.operations.V2DeleteBucketRequestBuilder;
import com.formance.formance_sdk.models.operations.V2DeleteBucketResponse;
import com.formance.formance_sdk.models.operations.V2DeleteExporterRequest;
import com.formance.formance_sdk.models.operations.V2DeleteExporterRequestBuilder;
import com.formance.formance_sdk.models.operations.V2DeleteExporterResponse;
import com.formance.formance_sdk.models.operations.V2DeleteLedgerMetadataRequest;
import com.formance.formance_sdk.models.operations.V2DeleteLedgerMetadataRequestBuilder;
import com.formance.formance_sdk.models.operations.V2DeleteLedgerMetadataResponse;
import com.formance.formance_sdk.models.operations.V2DeletePipelineRequest;
import com.formance.formance_sdk.models.operations.V2DeletePipelineRequestBuilder;
import com.formance.formance_sdk.models.operations.V2DeletePipelineResponse;
import com.formance.formance_sdk.models.operations.V2DeleteTransactionMetadataRequest;
import com.formance.formance_sdk.models.operations.V2DeleteTransactionMetadataRequestBuilder;
import com.formance.formance_sdk.models.operations.V2DeleteTransactionMetadataResponse;
import com.formance.formance_sdk.models.operations.V2ExportLogsRequest;
import com.formance.formance_sdk.models.operations.V2ExportLogsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ExportLogsResponse;
import com.formance.formance_sdk.models.operations.V2GetAccountRequest;
import com.formance.formance_sdk.models.operations.V2GetAccountRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetAccountResponse;
import com.formance.formance_sdk.models.operations.V2GetBalancesAggregatedRequest;
import com.formance.formance_sdk.models.operations.V2GetBalancesAggregatedRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetBalancesAggregatedResponse;
import com.formance.formance_sdk.models.operations.V2GetExporterStateRequest;
import com.formance.formance_sdk.models.operations.V2GetExporterStateRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetExporterStateResponse;
import com.formance.formance_sdk.models.operations.V2GetLedgerInfoRequest;
import com.formance.formance_sdk.models.operations.V2GetLedgerInfoRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetLedgerInfoResponse;
import com.formance.formance_sdk.models.operations.V2GetLedgerRequest;
import com.formance.formance_sdk.models.operations.V2GetLedgerRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetLedgerResponse;
import com.formance.formance_sdk.models.operations.V2GetPipelineStateRequest;
import com.formance.formance_sdk.models.operations.V2GetPipelineStateRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetPipelineStateResponse;
import com.formance.formance_sdk.models.operations.V2GetSchemaRequest;
import com.formance.formance_sdk.models.operations.V2GetSchemaRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetSchemaResponse;
import com.formance.formance_sdk.models.operations.V2GetTransactionRequest;
import com.formance.formance_sdk.models.operations.V2GetTransactionRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetTransactionResponse;
import com.formance.formance_sdk.models.operations.V2GetVolumesWithBalancesRequest;
import com.formance.formance_sdk.models.operations.V2GetVolumesWithBalancesRequestBuilder;
import com.formance.formance_sdk.models.operations.V2GetVolumesWithBalancesResponse;
import com.formance.formance_sdk.models.operations.V2ImportLogsRequest;
import com.formance.formance_sdk.models.operations.V2ImportLogsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ImportLogsResponse;
import com.formance.formance_sdk.models.operations.V2InsertSchemaRequest;
import com.formance.formance_sdk.models.operations.V2InsertSchemaRequestBuilder;
import com.formance.formance_sdk.models.operations.V2InsertSchemaResponse;
import com.formance.formance_sdk.models.operations.V2ListAccountsRequest;
import com.formance.formance_sdk.models.operations.V2ListAccountsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ListAccountsResponse;
import com.formance.formance_sdk.models.operations.V2ListExportersRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ListExportersResponse;
import com.formance.formance_sdk.models.operations.V2ListLedgersRequest;
import com.formance.formance_sdk.models.operations.V2ListLedgersRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ListLedgersResponse;
import com.formance.formance_sdk.models.operations.V2ListLogsRequest;
import com.formance.formance_sdk.models.operations.V2ListLogsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ListLogsResponse;
import com.formance.formance_sdk.models.operations.V2ListPipelinesRequest;
import com.formance.formance_sdk.models.operations.V2ListPipelinesRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ListPipelinesResponse;
import com.formance.formance_sdk.models.operations.V2ListSchemasRequest;
import com.formance.formance_sdk.models.operations.V2ListSchemasRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ListSchemasResponse;
import com.formance.formance_sdk.models.operations.V2ListTransactionsRequest;
import com.formance.formance_sdk.models.operations.V2ListTransactionsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ListTransactionsResponse;
import com.formance.formance_sdk.models.operations.V2ReadStatsRequest;
import com.formance.formance_sdk.models.operations.V2ReadStatsRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ReadStatsResponse;
import com.formance.formance_sdk.models.operations.V2ResetPipelineRequest;
import com.formance.formance_sdk.models.operations.V2ResetPipelineRequestBuilder;
import com.formance.formance_sdk.models.operations.V2ResetPipelineResponse;
import com.formance.formance_sdk.models.operations.V2RestoreBucketRequest;
import com.formance.formance_sdk.models.operations.V2RestoreBucketRequestBuilder;
import com.formance.formance_sdk.models.operations.V2RestoreBucketResponse;
import com.formance.formance_sdk.models.operations.V2RevertTransactionRequest;
import com.formance.formance_sdk.models.operations.V2RevertTransactionRequestBuilder;
import com.formance.formance_sdk.models.operations.V2RevertTransactionResponse;
import com.formance.formance_sdk.models.operations.V2RunQueryRequest;
import com.formance.formance_sdk.models.operations.V2RunQueryRequestBuilder;
import com.formance.formance_sdk.models.operations.V2RunQueryResponse;
import com.formance.formance_sdk.models.operations.V2StartPipelineRequest;
import com.formance.formance_sdk.models.operations.V2StartPipelineRequestBuilder;
import com.formance.formance_sdk.models.operations.V2StartPipelineResponse;
import com.formance.formance_sdk.models.operations.V2StopPipelineRequest;
import com.formance.formance_sdk.models.operations.V2StopPipelineRequestBuilder;
import com.formance.formance_sdk.models.operations.V2StopPipelineResponse;
import com.formance.formance_sdk.models.operations.V2UpdateExporterRequest;
import com.formance.formance_sdk.models.operations.V2UpdateExporterRequestBuilder;
import com.formance.formance_sdk.models.operations.V2UpdateExporterResponse;
import com.formance.formance_sdk.models.operations.V2UpdateLedgerMetadataRequest;
import com.formance.formance_sdk.models.operations.V2UpdateLedgerMetadataRequestBuilder;
import com.formance.formance_sdk.models.operations.V2UpdateLedgerMetadataResponse;
import com.formance.formance_sdk.operations.V2AddMetadataOnTransaction;
import com.formance.formance_sdk.operations.V2AddMetadataToAccount;
import com.formance.formance_sdk.operations.V2CountAccounts;
import com.formance.formance_sdk.operations.V2CountTransactions;
import com.formance.formance_sdk.operations.V2CreateBulk;
import com.formance.formance_sdk.operations.V2CreateExporter;
import com.formance.formance_sdk.operations.V2CreateLedger;
import com.formance.formance_sdk.operations.V2CreatePipeline;
import com.formance.formance_sdk.operations.V2CreateTransaction;
import com.formance.formance_sdk.operations.V2DeleteAccountMetadata;
import com.formance.formance_sdk.operations.V2DeleteBucket;
import com.formance.formance_sdk.operations.V2DeleteExporter;
import com.formance.formance_sdk.operations.V2DeleteLedgerMetadata;
import com.formance.formance_sdk.operations.V2DeletePipeline;
import com.formance.formance_sdk.operations.V2DeleteTransactionMetadata;
import com.formance.formance_sdk.operations.V2ExportLogs;
import com.formance.formance_sdk.operations.V2GetAccount;
import com.formance.formance_sdk.operations.V2GetBalancesAggregated;
import com.formance.formance_sdk.operations.V2GetExporterState;
import com.formance.formance_sdk.operations.V2GetLedger;
import com.formance.formance_sdk.operations.V2GetLedgerInfo;
import com.formance.formance_sdk.operations.V2GetPipelineState;
import com.formance.formance_sdk.operations.V2GetSchema;
import com.formance.formance_sdk.operations.V2GetTransaction;
import com.formance.formance_sdk.operations.V2GetVolumesWithBalances;
import com.formance.formance_sdk.operations.V2ImportLogs;
import com.formance.formance_sdk.operations.V2InsertSchema;
import com.formance.formance_sdk.operations.V2ListAccounts;
import com.formance.formance_sdk.operations.V2ListExporters;
import com.formance.formance_sdk.operations.V2ListLedgers;
import com.formance.formance_sdk.operations.V2ListLogs;
import com.formance.formance_sdk.operations.V2ListPipelines;
import com.formance.formance_sdk.operations.V2ListSchemas;
import com.formance.formance_sdk.operations.V2ListTransactions;
import com.formance.formance_sdk.operations.V2ReadStats;
import com.formance.formance_sdk.operations.V2ResetPipeline;
import com.formance.formance_sdk.operations.V2RestoreBucket;
import com.formance.formance_sdk.operations.V2RevertTransaction;
import com.formance.formance_sdk.operations.V2RunQuery;
import com.formance.formance_sdk.operations.V2StartPipeline;
import com.formance.formance_sdk.operations.V2StopPipeline;
import com.formance.formance_sdk.operations.V2UpdateExporter;
import com.formance.formance_sdk.operations.V2UpdateLedgerMetadata;
import com.formance.formance_sdk.utils.Headers;
import java.lang.String;
import java.util.Optional;


public class LedgerV2 {
    private static final Headers _headers = Headers.EMPTY;
    private final SDKConfiguration sdkConfiguration;

    LedgerV2(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    /**
     * Set the metadata of a transaction by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2AddMetadataOnTransactionRequestBuilder addMetadataOnTransaction() {
        return new V2AddMetadataOnTransactionRequestBuilder(sdkConfiguration);
    }

    /**
     * Set the metadata of a transaction by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2AddMetadataOnTransactionResponse addMetadataOnTransaction(V2AddMetadataOnTransactionRequest request) {
        return addMetadataOnTransaction(request, Optional.empty());
    }

    /**
     * Set the metadata of a transaction by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2AddMetadataOnTransactionResponse addMetadataOnTransaction(V2AddMetadataOnTransactionRequest request, Optional<String> serverURL) {
        RequestOperation<V2AddMetadataOnTransactionRequest, V2AddMetadataOnTransactionResponse> operation
              = new V2AddMetadataOnTransaction.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Add metadata to an account
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2AddMetadataToAccountRequestBuilder addMetadataToAccount() {
        return new V2AddMetadataToAccountRequestBuilder(sdkConfiguration);
    }

    /**
     * Add metadata to an account
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2AddMetadataToAccountResponse addMetadataToAccount(V2AddMetadataToAccountRequest request) {
        return addMetadataToAccount(request, Optional.empty());
    }

    /**
     * Add metadata to an account
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2AddMetadataToAccountResponse addMetadataToAccount(V2AddMetadataToAccountRequest request, Optional<String> serverURL) {
        RequestOperation<V2AddMetadataToAccountRequest, V2AddMetadataToAccountResponse> operation
              = new V2AddMetadataToAccount.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Count the accounts from a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2CountAccountsRequestBuilder countAccounts() {
        return new V2CountAccountsRequestBuilder(sdkConfiguration);
    }

    /**
     * Count the accounts from a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CountAccountsResponse countAccounts(V2CountAccountsRequest request) {
        return countAccounts(request, Optional.empty());
    }

    /**
     * Count the accounts from a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CountAccountsResponse countAccounts(V2CountAccountsRequest request, Optional<String> serverURL) {
        RequestOperation<V2CountAccountsRequest, V2CountAccountsResponse> operation
              = new V2CountAccounts.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Count the transactions from a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2CountTransactionsRequestBuilder countTransactions() {
        return new V2CountTransactionsRequestBuilder(sdkConfiguration);
    }

    /**
     * Count the transactions from a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CountTransactionsResponse countTransactions(V2CountTransactionsRequest request) {
        return countTransactions(request, Optional.empty());
    }

    /**
     * Count the transactions from a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CountTransactionsResponse countTransactions(V2CountTransactionsRequest request, Optional<String> serverURL) {
        RequestOperation<V2CountTransactionsRequest, V2CountTransactionsResponse> operation
              = new V2CountTransactions.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Bulk request
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2CreateBulkRequestBuilder createBulk() {
        return new V2CreateBulkRequestBuilder(sdkConfiguration);
    }

    /**
     * Bulk request
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateBulkResponse createBulk(V2CreateBulkRequest request) {
        return createBulk(request, Optional.empty());
    }

    /**
     * Bulk request
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateBulkResponse createBulk(V2CreateBulkRequest request, Optional<String> serverURL) {
        RequestOperation<V2CreateBulkRequest, V2CreateBulkResponse> operation
              = new V2CreateBulk.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create exporter
     * 
     * @return The call builder
     */
    public V2CreateExporterRequestBuilder createExporter() {
        return new V2CreateExporterRequestBuilder(sdkConfiguration);
    }

    /**
     * Create exporter
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateExporterResponse createExporter(V2ExporterConfiguration2 request) {
        return createExporter(request, Optional.empty());
    }

    /**
     * Create exporter
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateExporterResponse createExporter(V2ExporterConfiguration2 request, Optional<String> serverURL) {
        RequestOperation<V2ExporterConfiguration2, V2CreateExporterResponse> operation
              = new V2CreateExporter.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2CreateLedgerRequestBuilder createLedger() {
        return new V2CreateLedgerRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateLedgerResponse createLedger(V2CreateLedgerRequest request) {
        return createLedger(request, Optional.empty());
    }

    /**
     * Create a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateLedgerResponse createLedger(V2CreateLedgerRequest request, Optional<String> serverURL) {
        RequestOperation<V2CreateLedgerRequest, V2CreateLedgerResponse> operation
              = new V2CreateLedger.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create pipeline
     * 
     * @return The call builder
     */
    public V2CreatePipelineRequestBuilder createPipeline() {
        return new V2CreatePipelineRequestBuilder(sdkConfiguration);
    }

    /**
     * Create pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreatePipelineResponse createPipeline(V2CreatePipelineRequest request) {
        return createPipeline(request, Optional.empty());
    }

    /**
     * Create pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreatePipelineResponse createPipeline(V2CreatePipelineRequest request, Optional<String> serverURL) {
        RequestOperation<V2CreatePipelineRequest, V2CreatePipelineResponse> operation
              = new V2CreatePipeline.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Create a new transaction to a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2CreateTransactionRequestBuilder createTransaction() {
        return new V2CreateTransactionRequestBuilder(sdkConfiguration);
    }

    /**
     * Create a new transaction to a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateTransactionResponse createTransaction(V2CreateTransactionRequest request) {
        return createTransaction(request, Optional.empty());
    }

    /**
     * Create a new transaction to a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2CreateTransactionResponse createTransaction(V2CreateTransactionRequest request, Optional<String> serverURL) {
        RequestOperation<V2CreateTransactionRequest, V2CreateTransactionResponse> operation
              = new V2CreateTransaction.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete metadata by key
     * 
     * <p>Delete metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2DeleteAccountMetadataRequestBuilder deleteAccountMetadata() {
        return new V2DeleteAccountMetadataRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete metadata by key
     * 
     * <p>Delete metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteAccountMetadataResponse deleteAccountMetadata(V2DeleteAccountMetadataRequest request) {
        return deleteAccountMetadata(request, Optional.empty());
    }

    /**
     * Delete metadata by key
     * 
     * <p>Delete metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteAccountMetadataResponse deleteAccountMetadata(V2DeleteAccountMetadataRequest request, Optional<String> serverURL) {
        RequestOperation<V2DeleteAccountMetadataRequest, V2DeleteAccountMetadataResponse> operation
              = new V2DeleteAccountMetadata.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete bucket
     * 
     * <p>Delete a bucket by marking all ledgers in the bucket as deleted (soft delete). All ledgers in the
     * bucket will have their deleted_at field set to the current timestamp.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2DeleteBucketRequestBuilder deleteBucket() {
        return new V2DeleteBucketRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete bucket
     * 
     * <p>Delete a bucket by marking all ledgers in the bucket as deleted (soft delete). All ledgers in the
     * bucket will have their deleted_at field set to the current timestamp.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteBucketResponse deleteBucket(V2DeleteBucketRequest request) {
        return deleteBucket(request, Optional.empty());
    }

    /**
     * Delete bucket
     * 
     * <p>Delete a bucket by marking all ledgers in the bucket as deleted (soft delete). All ledgers in the
     * bucket will have their deleted_at field set to the current timestamp.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteBucketResponse deleteBucket(V2DeleteBucketRequest request, Optional<String> serverURL) {
        RequestOperation<V2DeleteBucketRequest, V2DeleteBucketResponse> operation
              = new V2DeleteBucket.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete exporter
     * 
     * @return The call builder
     */
    public V2DeleteExporterRequestBuilder deleteExporter() {
        return new V2DeleteExporterRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete exporter
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteExporterResponse deleteExporter(V2DeleteExporterRequest request) {
        return deleteExporter(request, Optional.empty());
    }

    /**
     * Delete exporter
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteExporterResponse deleteExporter(V2DeleteExporterRequest request, Optional<String> serverURL) {
        RequestOperation<V2DeleteExporterRequest, V2DeleteExporterResponse> operation
              = new V2DeleteExporter.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete ledger metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2DeleteLedgerMetadataRequestBuilder deleteLedgerMetadata() {
        return new V2DeleteLedgerMetadataRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete ledger metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteLedgerMetadataResponse deleteLedgerMetadata(V2DeleteLedgerMetadataRequest request) {
        return deleteLedgerMetadata(request, Optional.empty());
    }

    /**
     * Delete ledger metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteLedgerMetadataResponse deleteLedgerMetadata(V2DeleteLedgerMetadataRequest request, Optional<String> serverURL) {
        RequestOperation<V2DeleteLedgerMetadataRequest, V2DeleteLedgerMetadataResponse> operation
              = new V2DeleteLedgerMetadata.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete pipeline
     * 
     * @return The call builder
     */
    public V2DeletePipelineRequestBuilder deletePipeline() {
        return new V2DeletePipelineRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeletePipelineResponse deletePipeline(V2DeletePipelineRequest request) {
        return deletePipeline(request, Optional.empty());
    }

    /**
     * Delete pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeletePipelineResponse deletePipeline(V2DeletePipelineRequest request, Optional<String> serverURL) {
        RequestOperation<V2DeletePipelineRequest, V2DeletePipelineResponse> operation
              = new V2DeletePipeline.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Delete metadata by key
     * 
     * <p>Delete metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2DeleteTransactionMetadataRequestBuilder deleteTransactionMetadata() {
        return new V2DeleteTransactionMetadataRequestBuilder(sdkConfiguration);
    }

    /**
     * Delete metadata by key
     * 
     * <p>Delete metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteTransactionMetadataResponse deleteTransactionMetadata(V2DeleteTransactionMetadataRequest request) {
        return deleteTransactionMetadata(request, Optional.empty());
    }

    /**
     * Delete metadata by key
     * 
     * <p>Delete metadata by key
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2DeleteTransactionMetadataResponse deleteTransactionMetadata(V2DeleteTransactionMetadataRequest request, Optional<String> serverURL) {
        RequestOperation<V2DeleteTransactionMetadataRequest, V2DeleteTransactionMetadataResponse> operation
              = new V2DeleteTransactionMetadata.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Export logs
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ExportLogsRequestBuilder exportLogs() {
        return new V2ExportLogsRequestBuilder(sdkConfiguration);
    }

    /**
     * Export logs
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ExportLogsResponse exportLogs(V2ExportLogsRequest request) {
        return exportLogs(request, Optional.empty());
    }

    /**
     * Export logs
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ExportLogsResponse exportLogs(V2ExportLogsRequest request, Optional<String> serverURL) {
        RequestOperation<V2ExportLogsRequest, V2ExportLogsResponse> operation
              = new V2ExportLogs.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get account by its address
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2GetAccountRequestBuilder getAccount() {
        return new V2GetAccountRequestBuilder(sdkConfiguration);
    }

    /**
     * Get account by its address
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetAccountResponse getAccount(V2GetAccountRequest request) {
        return getAccount(request, Optional.empty());
    }

    /**
     * Get account by its address
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetAccountResponse getAccount(V2GetAccountRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetAccountRequest, V2GetAccountResponse> operation
              = new V2GetAccount.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get the aggregated balances from selected accounts
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2GetBalancesAggregatedRequestBuilder getBalancesAggregated() {
        return new V2GetBalancesAggregatedRequestBuilder(sdkConfiguration);
    }

    /**
     * Get the aggregated balances from selected accounts
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetBalancesAggregatedResponse getBalancesAggregated(V2GetBalancesAggregatedRequest request) {
        return getBalancesAggregated(request, Optional.empty());
    }

    /**
     * Get the aggregated balances from selected accounts
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetBalancesAggregatedResponse getBalancesAggregated(V2GetBalancesAggregatedRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetBalancesAggregatedRequest, V2GetBalancesAggregatedResponse> operation
              = new V2GetBalancesAggregated.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get exporter state
     * 
     * @return The call builder
     */
    public V2GetExporterStateRequestBuilder getExporterState() {
        return new V2GetExporterStateRequestBuilder(sdkConfiguration);
    }

    /**
     * Get exporter state
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetExporterStateResponse getExporterState(V2GetExporterStateRequest request) {
        return getExporterState(request, Optional.empty());
    }

    /**
     * Get exporter state
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetExporterStateResponse getExporterState(V2GetExporterStateRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetExporterStateRequest, V2GetExporterStateResponse> operation
              = new V2GetExporterState.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2GetLedgerRequestBuilder getLedger() {
        return new V2GetLedgerRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetLedgerResponse getLedger(V2GetLedgerRequest request) {
        return getLedger(request, Optional.empty());
    }

    /**
     * Get a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetLedgerResponse getLedger(V2GetLedgerRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetLedgerRequest, V2GetLedgerResponse> operation
              = new V2GetLedger.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get information about a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2GetLedgerInfoRequestBuilder getLedgerInfo() {
        return new V2GetLedgerInfoRequestBuilder(sdkConfiguration);
    }

    /**
     * Get information about a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetLedgerInfoResponse getLedgerInfo(V2GetLedgerInfoRequest request) {
        return getLedgerInfo(request, Optional.empty());
    }

    /**
     * Get information about a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetLedgerInfoResponse getLedgerInfo(V2GetLedgerInfoRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetLedgerInfoRequest, V2GetLedgerInfoResponse> operation
              = new V2GetLedgerInfo.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get pipeline state
     * 
     * @return The call builder
     */
    public V2GetPipelineStateRequestBuilder getPipelineState() {
        return new V2GetPipelineStateRequestBuilder(sdkConfiguration);
    }

    /**
     * Get pipeline state
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetPipelineStateResponse getPipelineState(V2GetPipelineStateRequest request) {
        return getPipelineState(request, Optional.empty());
    }

    /**
     * Get pipeline state
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetPipelineStateResponse getPipelineState(V2GetPipelineStateRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetPipelineStateRequest, V2GetPipelineStateResponse> operation
              = new V2GetPipelineState.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get a schema for a ledger by version
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2GetSchemaRequestBuilder getSchema() {
        return new V2GetSchemaRequestBuilder(sdkConfiguration);
    }

    /**
     * Get a schema for a ledger by version
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetSchemaResponse getSchema(V2GetSchemaRequest request) {
        return getSchema(request, Optional.empty());
    }

    /**
     * Get a schema for a ledger by version
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetSchemaResponse getSchema(V2GetSchemaRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetSchemaRequest, V2GetSchemaResponse> operation
              = new V2GetSchema.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get transaction from a ledger by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2GetTransactionRequestBuilder getTransaction() {
        return new V2GetTransactionRequestBuilder(sdkConfiguration);
    }

    /**
     * Get transaction from a ledger by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetTransactionResponse getTransaction(V2GetTransactionRequest request) {
        return getTransaction(request, Optional.empty());
    }

    /**
     * Get transaction from a ledger by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetTransactionResponse getTransaction(V2GetTransactionRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetTransactionRequest, V2GetTransactionResponse> operation
              = new V2GetTransaction.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get list of volumes with balances for (account/asset)
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2GetVolumesWithBalancesRequestBuilder getVolumesWithBalances() {
        return new V2GetVolumesWithBalancesRequestBuilder(sdkConfiguration);
    }

    /**
     * Get list of volumes with balances for (account/asset)
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetVolumesWithBalancesResponse getVolumesWithBalances(V2GetVolumesWithBalancesRequest request) {
        return getVolumesWithBalances(request, Optional.empty());
    }

    /**
     * Get list of volumes with balances for (account/asset)
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2GetVolumesWithBalancesResponse getVolumesWithBalances(V2GetVolumesWithBalancesRequest request, Optional<String> serverURL) {
        RequestOperation<V2GetVolumesWithBalancesRequest, V2GetVolumesWithBalancesResponse> operation
              = new V2GetVolumesWithBalances.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Returns a builder to make a request.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ImportLogsRequestBuilder importLogs() {
        return new V2ImportLogsRequestBuilder(sdkConfiguration);
    }

    /**
     * Makes a request (required parameters only).
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ImportLogsResponse importLogs(V2ImportLogsRequest request) {
        return importLogs(request, Optional.empty());
    }

    /**
     * Makes a request.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ImportLogsResponse importLogs(V2ImportLogsRequest request, Optional<String> serverURL) {
        RequestOperation<V2ImportLogsRequest, V2ImportLogsResponse> operation
              = new V2ImportLogs.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Insert a schema for a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2InsertSchemaRequestBuilder insertSchema() {
        return new V2InsertSchemaRequestBuilder(sdkConfiguration);
    }

    /**
     * Insert a schema for a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2InsertSchemaResponse insertSchema(V2InsertSchemaRequest request) {
        return insertSchema(request, Optional.empty());
    }

    /**
     * Insert a schema for a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2InsertSchemaResponse insertSchema(V2InsertSchemaRequest request, Optional<String> serverURL) {
        RequestOperation<V2InsertSchemaRequest, V2InsertSchemaResponse> operation
              = new V2InsertSchema.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List accounts from a ledger
     * 
     * <p>List accounts from a ledger, sorted by address in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ListAccountsRequestBuilder listAccounts() {
        return new V2ListAccountsRequestBuilder(sdkConfiguration);
    }

    /**
     * List accounts from a ledger
     * 
     * <p>List accounts from a ledger, sorted by address in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListAccountsResponse listAccounts(V2ListAccountsRequest request) {
        return listAccounts(request, Optional.empty());
    }

    /**
     * List accounts from a ledger
     * 
     * <p>List accounts from a ledger, sorted by address in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListAccountsResponse listAccounts(V2ListAccountsRequest request, Optional<String> serverURL) {
        RequestOperation<V2ListAccountsRequest, V2ListAccountsResponse> operation
              = new V2ListAccounts.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List exporters
     * 
     * @return The call builder
     */
    public V2ListExportersRequestBuilder listExporters() {
        return new V2ListExportersRequestBuilder(sdkConfiguration);
    }

    /**
     * List exporters
     * 
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListExportersResponse listExportersDirect() {
        return listExporters(Optional.empty());
    }

    /**
     * List exporters
     * 
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListExportersResponse listExporters(Optional<String> serverURL) {
        RequestlessOperation<V2ListExportersResponse> operation
            = new V2ListExporters.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest());
    }

    /**
     * List ledgers
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ListLedgersRequestBuilder listLedgers() {
        return new V2ListLedgersRequestBuilder(sdkConfiguration);
    }

    /**
     * List ledgers
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListLedgersResponse listLedgers(V2ListLedgersRequest request) {
        return listLedgers(request, Optional.empty());
    }

    /**
     * List ledgers
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListLedgersResponse listLedgers(V2ListLedgersRequest request, Optional<String> serverURL) {
        RequestOperation<V2ListLedgersRequest, V2ListLedgersResponse> operation
              = new V2ListLedgers.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List the logs from a ledger
     * 
     * <p>List the logs from a ledger, sorted by ID in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ListLogsRequestBuilder listLogs() {
        return new V2ListLogsRequestBuilder(sdkConfiguration);
    }

    /**
     * List the logs from a ledger
     * 
     * <p>List the logs from a ledger, sorted by ID in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListLogsResponse listLogs(V2ListLogsRequest request) {
        return listLogs(request, Optional.empty());
    }

    /**
     * List the logs from a ledger
     * 
     * <p>List the logs from a ledger, sorted by ID in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListLogsResponse listLogs(V2ListLogsRequest request, Optional<String> serverURL) {
        RequestOperation<V2ListLogsRequest, V2ListLogsResponse> operation
              = new V2ListLogs.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List pipelines
     * 
     * @return The call builder
     */
    public V2ListPipelinesRequestBuilder listPipelines() {
        return new V2ListPipelinesRequestBuilder(sdkConfiguration);
    }

    /**
     * List pipelines
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListPipelinesResponse listPipelines(V2ListPipelinesRequest request) {
        return listPipelines(request, Optional.empty());
    }

    /**
     * List pipelines
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListPipelinesResponse listPipelines(V2ListPipelinesRequest request, Optional<String> serverURL) {
        RequestOperation<V2ListPipelinesRequest, V2ListPipelinesResponse> operation
              = new V2ListPipelines.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List all schemas for a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ListSchemasRequestBuilder listSchemas() {
        return new V2ListSchemasRequestBuilder(sdkConfiguration);
    }

    /**
     * List all schemas for a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListSchemasResponse listSchemas(V2ListSchemasRequest request) {
        return listSchemas(request, Optional.empty());
    }

    /**
     * List all schemas for a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListSchemasResponse listSchemas(V2ListSchemasRequest request, Optional<String> serverURL) {
        RequestOperation<V2ListSchemasRequest, V2ListSchemasResponse> operation
              = new V2ListSchemas.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * List transactions from a ledger
     * 
     * <p>List transactions from a ledger, sorted by id in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ListTransactionsRequestBuilder listTransactions() {
        return new V2ListTransactionsRequestBuilder(sdkConfiguration);
    }

    /**
     * List transactions from a ledger
     * 
     * <p>List transactions from a ledger, sorted by id in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListTransactionsResponse listTransactions(V2ListTransactionsRequest request) {
        return listTransactions(request, Optional.empty());
    }

    /**
     * List transactions from a ledger
     * 
     * <p>List transactions from a ledger, sorted by id in descending order.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ListTransactionsResponse listTransactions(V2ListTransactionsRequest request, Optional<String> serverURL) {
        RequestOperation<V2ListTransactionsRequest, V2ListTransactionsResponse> operation
              = new V2ListTransactions.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Get statistics from a ledger
     * 
     * <p>Get statistics from a ledger. (aggregate metrics on accounts and transactions)
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2ReadStatsRequestBuilder readStats() {
        return new V2ReadStatsRequestBuilder(sdkConfiguration);
    }

    /**
     * Get statistics from a ledger
     * 
     * <p>Get statistics from a ledger. (aggregate metrics on accounts and transactions)
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ReadStatsResponse readStats(V2ReadStatsRequest request) {
        return readStats(request, Optional.empty());
    }

    /**
     * Get statistics from a ledger
     * 
     * <p>Get statistics from a ledger. (aggregate metrics on accounts and transactions)
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ReadStatsResponse readStats(V2ReadStatsRequest request, Optional<String> serverURL) {
        RequestOperation<V2ReadStatsRequest, V2ReadStatsResponse> operation
              = new V2ReadStats.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Reset pipeline
     * 
     * @return The call builder
     */
    public V2ResetPipelineRequestBuilder resetPipeline() {
        return new V2ResetPipelineRequestBuilder(sdkConfiguration);
    }

    /**
     * Reset pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ResetPipelineResponse resetPipeline(V2ResetPipelineRequest request) {
        return resetPipeline(request, Optional.empty());
    }

    /**
     * Reset pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2ResetPipelineResponse resetPipeline(V2ResetPipelineRequest request, Optional<String> serverURL) {
        RequestOperation<V2ResetPipelineRequest, V2ResetPipelineResponse> operation
              = new V2ResetPipeline.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Restore bucket
     * 
     * <p>Restore a deleted bucket by unmarking all ledgers in the bucket as deleted. All ledgers in the
     * bucket will have their deleted_at field set to NULL.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2RestoreBucketRequestBuilder restoreBucket() {
        return new V2RestoreBucketRequestBuilder(sdkConfiguration);
    }

    /**
     * Restore bucket
     * 
     * <p>Restore a deleted bucket by unmarking all ledgers in the bucket as deleted. All ledgers in the
     * bucket will have their deleted_at field set to NULL.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2RestoreBucketResponse restoreBucket(V2RestoreBucketRequest request) {
        return restoreBucket(request, Optional.empty());
    }

    /**
     * Restore bucket
     * 
     * <p>Restore a deleted bucket by unmarking all ledgers in the bucket as deleted. All ledgers in the
     * bucket will have their deleted_at field set to NULL.
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2RestoreBucketResponse restoreBucket(V2RestoreBucketRequest request, Optional<String> serverURL) {
        RequestOperation<V2RestoreBucketRequest, V2RestoreBucketResponse> operation
              = new V2RestoreBucket.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Revert a ledger transaction by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2RevertTransactionRequestBuilder revertTransaction() {
        return new V2RevertTransactionRequestBuilder(sdkConfiguration);
    }

    /**
     * Revert a ledger transaction by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2RevertTransactionResponse revertTransaction(V2RevertTransactionRequest request) {
        return revertTransaction(request, Optional.empty());
    }

    /**
     * Revert a ledger transaction by its ID
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2RevertTransactionResponse revertTransaction(V2RevertTransactionRequest request, Optional<String> serverURL) {
        RequestOperation<V2RevertTransactionRequest, V2RevertTransactionResponse> operation
              = new V2RevertTransaction.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Run a query template
     * 
     * <p>Run a query template on a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2RunQueryRequestBuilder runQuery() {
        return new V2RunQueryRequestBuilder(sdkConfiguration);
    }

    /**
     * Run a query template
     * 
     * <p>Run a query template on a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2RunQueryResponse runQuery(V2RunQueryRequest request) {
        return runQuery(request, Optional.empty());
    }

    /**
     * Run a query template
     * 
     * <p>Run a query template on a ledger
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2RunQueryResponse runQuery(V2RunQueryRequest request, Optional<String> serverURL) {
        RequestOperation<V2RunQueryRequest, V2RunQueryResponse> operation
              = new V2RunQuery.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Start pipeline
     * 
     * @return The call builder
     */
    public V2StartPipelineRequestBuilder startPipeline() {
        return new V2StartPipelineRequestBuilder(sdkConfiguration);
    }

    /**
     * Start pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2StartPipelineResponse startPipeline(V2StartPipelineRequest request) {
        return startPipeline(request, Optional.empty());
    }

    /**
     * Start pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2StartPipelineResponse startPipeline(V2StartPipelineRequest request, Optional<String> serverURL) {
        RequestOperation<V2StartPipelineRequest, V2StartPipelineResponse> operation
              = new V2StartPipeline.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Stop pipeline
     * 
     * @return The call builder
     */
    public V2StopPipelineRequestBuilder stopPipeline() {
        return new V2StopPipelineRequestBuilder(sdkConfiguration);
    }

    /**
     * Stop pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2StopPipelineResponse stopPipeline(V2StopPipelineRequest request) {
        return stopPipeline(request, Optional.empty());
    }

    /**
     * Stop pipeline
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2StopPipelineResponse stopPipeline(V2StopPipelineRequest request, Optional<String> serverURL) {
        RequestOperation<V2StopPipelineRequest, V2StopPipelineResponse> operation
              = new V2StopPipeline.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update exporter
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2UpdateExporterRequestBuilder updateExporter() {
        return new V2UpdateExporterRequestBuilder(sdkConfiguration);
    }

    /**
     * Update exporter
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2UpdateExporterResponse updateExporter(V2UpdateExporterRequest request) {
        return updateExporter(request, Optional.empty());
    }

    /**
     * Update exporter
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2UpdateExporterResponse updateExporter(V2UpdateExporterRequest request, Optional<String> serverURL) {
        RequestOperation<V2UpdateExporterRequest, V2UpdateExporterResponse> operation
              = new V2UpdateExporter.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

    /**
     * Update ledger metadata
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @return The call builder
     */
    public V2UpdateLedgerMetadataRequestBuilder updateLedgerMetadata() {
        return new V2UpdateLedgerMetadataRequestBuilder(sdkConfiguration);
    }

    /**
     * Update ledger metadata
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2UpdateLedgerMetadataResponse updateLedgerMetadata(V2UpdateLedgerMetadataRequest request) {
        return updateLedgerMetadata(request, Optional.empty());
    }

    /**
     * Update ledger metadata
     * 
     * <p>If set, this operation will use Security#clientID from the global security.
     * 
     * @param request The request object containing all the parameters for the API call.
     * @param serverURL Overrides the server URL.
     * @return The response from the API call
     * @throws RuntimeException subclass if the API call fails
     */
    public V2UpdateLedgerMetadataResponse updateLedgerMetadata(V2UpdateLedgerMetadataRequest request, Optional<String> serverURL) {
        RequestOperation<V2UpdateLedgerMetadataRequest, V2UpdateLedgerMetadataResponse> operation
              = new V2UpdateLedgerMetadata.Sync(sdkConfiguration, serverURL, _headers);
        return operation.handleResponse(operation.doRequest(request));
    }

}
