/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;


public class OrchestrationAccount {

    @JsonProperty("address")
    private String address;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("effectiveVolumes")
    private Optional<? extends Map<String, Volume>> effectiveVolumes;

    @JsonProperty("metadata")
    private Map<String, String> metadata;

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("volumes")
    private Optional<? extends Map<String, Volume>> volumes;

    @JsonCreator
    public OrchestrationAccount(
            @JsonProperty("address") String address,
            @JsonProperty("effectiveVolumes") Optional<? extends Map<String, Volume>> effectiveVolumes,
            @JsonProperty("metadata") Map<String, String> metadata,
            @JsonProperty("volumes") Optional<? extends Map<String, Volume>> volumes) {
        Utils.checkNotNull(address, "address");
        Utils.checkNotNull(effectiveVolumes, "effectiveVolumes");
        metadata = Utils.emptyMapIfNull(metadata);
        Utils.checkNotNull(volumes, "volumes");
        this.address = address;
        this.effectiveVolumes = effectiveVolumes;
        this.metadata = metadata;
        this.volumes = volumes;
    }
    
    public OrchestrationAccount(
            String address,
            Map<String, String> metadata) {
        this(address, Optional.empty(), metadata, Optional.empty());
    }

    @JsonIgnore
    public String address() {
        return address;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Volume>> effectiveVolumes() {
        return (Optional<Map<String, Volume>>) effectiveVolumes;
    }

    @JsonIgnore
    public Map<String, String> metadata() {
        return metadata;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Volume>> volumes() {
        return (Optional<Map<String, Volume>>) volumes;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public OrchestrationAccount withAddress(String address) {
        Utils.checkNotNull(address, "address");
        this.address = address;
        return this;
    }

    public OrchestrationAccount withEffectiveVolumes(Map<String, Volume> effectiveVolumes) {
        Utils.checkNotNull(effectiveVolumes, "effectiveVolumes");
        this.effectiveVolumes = Optional.ofNullable(effectiveVolumes);
        return this;
    }

    public OrchestrationAccount withEffectiveVolumes(Optional<? extends Map<String, Volume>> effectiveVolumes) {
        Utils.checkNotNull(effectiveVolumes, "effectiveVolumes");
        this.effectiveVolumes = effectiveVolumes;
        return this;
    }

    public OrchestrationAccount withMetadata(Map<String, String> metadata) {
        Utils.checkNotNull(metadata, "metadata");
        this.metadata = metadata;
        return this;
    }

    public OrchestrationAccount withVolumes(Map<String, Volume> volumes) {
        Utils.checkNotNull(volumes, "volumes");
        this.volumes = Optional.ofNullable(volumes);
        return this;
    }

    public OrchestrationAccount withVolumes(Optional<? extends Map<String, Volume>> volumes) {
        Utils.checkNotNull(volumes, "volumes");
        this.volumes = volumes;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        OrchestrationAccount other = (OrchestrationAccount) o;
        return 
            Objects.deepEquals(this.address, other.address) &&
            Objects.deepEquals(this.effectiveVolumes, other.effectiveVolumes) &&
            Objects.deepEquals(this.metadata, other.metadata) &&
            Objects.deepEquals(this.volumes, other.volumes);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            address,
            effectiveVolumes,
            metadata,
            volumes);
    }
    
    @Override
    public String toString() {
        return Utils.toString(OrchestrationAccount.class,
                "address", address,
                "effectiveVolumes", effectiveVolumes,
                "metadata", metadata,
                "volumes", volumes);
    }
    
    public final static class Builder {
 
        private String address;
 
        private Optional<? extends Map<String, Volume>> effectiveVolumes = Optional.empty();
 
        private Map<String, String> metadata;
 
        private Optional<? extends Map<String, Volume>> volumes = Optional.empty();  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder address(String address) {
            Utils.checkNotNull(address, "address");
            this.address = address;
            return this;
        }

        public Builder effectiveVolumes(Map<String, Volume> effectiveVolumes) {
            Utils.checkNotNull(effectiveVolumes, "effectiveVolumes");
            this.effectiveVolumes = Optional.ofNullable(effectiveVolumes);
            return this;
        }

        public Builder effectiveVolumes(Optional<? extends Map<String, Volume>> effectiveVolumes) {
            Utils.checkNotNull(effectiveVolumes, "effectiveVolumes");
            this.effectiveVolumes = effectiveVolumes;
            return this;
        }

        public Builder metadata(Map<String, String> metadata) {
            Utils.checkNotNull(metadata, "metadata");
            this.metadata = metadata;
            return this;
        }

        public Builder volumes(Map<String, Volume> volumes) {
            Utils.checkNotNull(volumes, "volumes");
            this.volumes = Optional.ofNullable(volumes);
            return this;
        }

        public Builder volumes(Optional<? extends Map<String, Volume>> volumes) {
            Utils.checkNotNull(volumes, "volumes");
            this.volumes = volumes;
            return this;
        }
        
        public OrchestrationAccount build() {
            return new OrchestrationAccount(
                address,
                effectiveVolumes,
                metadata,
                volumes);
        }
    }
}

