/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.core.type.TypeReference;
import com.formance.formance_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class Pool {

    @JsonProperty("accounts")
    private java.util.List<String> accounts;

    @JsonProperty("id")
    private String id;

    @JsonProperty("name")
    private String name;

    public Pool(
            @JsonProperty("accounts") java.util.List<String> accounts,
            @JsonProperty("id") String id,
            @JsonProperty("name") String name) {
        Utils.checkNotNull(accounts, "accounts");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(name, "name");
        this.accounts = accounts;
        this.id = id;
        this.name = name;
    }

    public java.util.List<String> accounts() {
        return accounts;
    }

    public String id() {
        return id;
    }

    public String name() {
        return name;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public Pool withAccounts(java.util.List<String> accounts) {
        Utils.checkNotNull(accounts, "accounts");
        this.accounts = accounts;
        return this;
    }

    public Pool withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public Pool withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Pool other = (Pool) o;
        return 
            java.util.Objects.deepEquals(this.accounts, other.accounts) &&
            java.util.Objects.deepEquals(this.id, other.id) &&
            java.util.Objects.deepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            accounts,
            id,
            name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Pool.class,
                "accounts", accounts,
                "id", id,
                "name", name);
    }
    
    public final static class Builder {
 
        private java.util.List<String> accounts;
 
        private String id;
 
        private String name;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder accounts(java.util.List<String> accounts) {
            Utils.checkNotNull(accounts, "accounts");
            this.accounts = accounts;
            return this;
        }

        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }
        
        public Pool build() {
            return new Pool(
                accounts,
                id,
                name);
        }
    }
}

