/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Boolean;
import java.lang.Long;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.Optional;


public class QueryTemplateVolumeParams {
    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("cursor")
    private Optional<String> cursor;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("expand")
    private Optional<String> expand;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("groupBy")
    private Optional<Long> groupBy;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("insertionDate")
    private Optional<Boolean> insertionDate;

    /**
     * The maximum number of results to return per page.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pageSize")
    private Optional<Long> pageSize;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("pit")
    private Optional<OffsetDateTime> pit;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("resource")
    private Optional<? extends V2QueryParamsResourceVolumes> resource;

    /**
     * Sort results using a field name and order (ascending or descending).
     * Format: `&lt;field&gt;:&lt;order&gt;`, where `&lt;field&gt;` is the field name and `&lt;order&gt;`
     * is either `asc` or `desc`.
     */
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("sort")
    private Optional<String> sort;

    @JsonCreator
    public QueryTemplateVolumeParams(
            @JsonProperty("cursor") Optional<String> cursor,
            @JsonProperty("expand") Optional<String> expand,
            @JsonProperty("groupBy") Optional<Long> groupBy,
            @JsonProperty("insertionDate") Optional<Boolean> insertionDate,
            @JsonProperty("pageSize") Optional<Long> pageSize,
            @JsonProperty("pit") Optional<OffsetDateTime> pit,
            @JsonProperty("resource") Optional<? extends V2QueryParamsResourceVolumes> resource,
            @JsonProperty("sort") Optional<String> sort) {
        Utils.checkNotNull(cursor, "cursor");
        Utils.checkNotNull(expand, "expand");
        Utils.checkNotNull(groupBy, "groupBy");
        Utils.checkNotNull(insertionDate, "insertionDate");
        Utils.checkNotNull(pageSize, "pageSize");
        Utils.checkNotNull(pit, "pit");
        Utils.checkNotNull(resource, "resource");
        Utils.checkNotNull(sort, "sort");
        this.cursor = cursor;
        this.expand = expand;
        this.groupBy = groupBy;
        this.insertionDate = insertionDate;
        this.pageSize = pageSize;
        this.pit = pit;
        this.resource = resource;
        this.sort = sort;
    }
    
    public QueryTemplateVolumeParams() {
        this(Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty(), Optional.empty(),
            Optional.empty(), Optional.empty());
    }

    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     */
    @JsonIgnore
    public Optional<String> cursor() {
        return cursor;
    }

    @JsonIgnore
    public Optional<String> expand() {
        return expand;
    }

    @JsonIgnore
    public Optional<Long> groupBy() {
        return groupBy;
    }

    @JsonIgnore
    public Optional<Boolean> insertionDate() {
        return insertionDate;
    }

    /**
     * The maximum number of results to return per page.
     */
    @JsonIgnore
    public Optional<Long> pageSize() {
        return pageSize;
    }

    @JsonIgnore
    public Optional<OffsetDateTime> pit() {
        return pit;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<V2QueryParamsResourceVolumes> resource() {
        return (Optional<V2QueryParamsResourceVolumes>) resource;
    }

    /**
     * Sort results using a field name and order (ascending or descending).
     * Format: `&lt;field&gt;:&lt;order&gt;`, where `&lt;field&gt;` is the field name and `&lt;order&gt;`
     * is either `asc` or `desc`.
     */
    @JsonIgnore
    public Optional<String> sort() {
        return sort;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     */
    public QueryTemplateVolumeParams withCursor(String cursor) {
        Utils.checkNotNull(cursor, "cursor");
        this.cursor = Optional.ofNullable(cursor);
        return this;
    }


    /**
     * Parameter used in pagination requests. Maximum page size is set to 15.
     * Set to the value of next for the next page of results.
     * Set to the value of previous for the previous page of results.
     * No other parameters can be set when this parameter is set.
     */
    public QueryTemplateVolumeParams withCursor(Optional<String> cursor) {
        Utils.checkNotNull(cursor, "cursor");
        this.cursor = cursor;
        return this;
    }

    public QueryTemplateVolumeParams withExpand(String expand) {
        Utils.checkNotNull(expand, "expand");
        this.expand = Optional.ofNullable(expand);
        return this;
    }


    public QueryTemplateVolumeParams withExpand(Optional<String> expand) {
        Utils.checkNotNull(expand, "expand");
        this.expand = expand;
        return this;
    }

    public QueryTemplateVolumeParams withGroupBy(long groupBy) {
        Utils.checkNotNull(groupBy, "groupBy");
        this.groupBy = Optional.ofNullable(groupBy);
        return this;
    }


    public QueryTemplateVolumeParams withGroupBy(Optional<Long> groupBy) {
        Utils.checkNotNull(groupBy, "groupBy");
        this.groupBy = groupBy;
        return this;
    }

    public QueryTemplateVolumeParams withInsertionDate(boolean insertionDate) {
        Utils.checkNotNull(insertionDate, "insertionDate");
        this.insertionDate = Optional.ofNullable(insertionDate);
        return this;
    }


    public QueryTemplateVolumeParams withInsertionDate(Optional<Boolean> insertionDate) {
        Utils.checkNotNull(insertionDate, "insertionDate");
        this.insertionDate = insertionDate;
        return this;
    }

    /**
     * The maximum number of results to return per page.
     */
    public QueryTemplateVolumeParams withPageSize(long pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = Optional.ofNullable(pageSize);
        return this;
    }


    /**
     * The maximum number of results to return per page.
     */
    public QueryTemplateVolumeParams withPageSize(Optional<Long> pageSize) {
        Utils.checkNotNull(pageSize, "pageSize");
        this.pageSize = pageSize;
        return this;
    }

    public QueryTemplateVolumeParams withPit(OffsetDateTime pit) {
        Utils.checkNotNull(pit, "pit");
        this.pit = Optional.ofNullable(pit);
        return this;
    }


    public QueryTemplateVolumeParams withPit(Optional<OffsetDateTime> pit) {
        Utils.checkNotNull(pit, "pit");
        this.pit = pit;
        return this;
    }

    public QueryTemplateVolumeParams withResource(V2QueryParamsResourceVolumes resource) {
        Utils.checkNotNull(resource, "resource");
        this.resource = Optional.ofNullable(resource);
        return this;
    }


    public QueryTemplateVolumeParams withResource(Optional<? extends V2QueryParamsResourceVolumes> resource) {
        Utils.checkNotNull(resource, "resource");
        this.resource = resource;
        return this;
    }

    /**
     * Sort results using a field name and order (ascending or descending).
     * Format: `&lt;field&gt;:&lt;order&gt;`, where `&lt;field&gt;` is the field name and `&lt;order&gt;`
     * is either `asc` or `desc`.
     */
    public QueryTemplateVolumeParams withSort(String sort) {
        Utils.checkNotNull(sort, "sort");
        this.sort = Optional.ofNullable(sort);
        return this;
    }


    /**
     * Sort results using a field name and order (ascending or descending).
     * Format: `&lt;field&gt;:&lt;order&gt;`, where `&lt;field&gt;` is the field name and `&lt;order&gt;`
     * is either `asc` or `desc`.
     */
    public QueryTemplateVolumeParams withSort(Optional<String> sort) {
        Utils.checkNotNull(sort, "sort");
        this.sort = sort;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        QueryTemplateVolumeParams other = (QueryTemplateVolumeParams) o;
        return 
            Utils.enhancedDeepEquals(this.cursor, other.cursor) &&
            Utils.enhancedDeepEquals(this.expand, other.expand) &&
            Utils.enhancedDeepEquals(this.groupBy, other.groupBy) &&
            Utils.enhancedDeepEquals(this.insertionDate, other.insertionDate) &&
            Utils.enhancedDeepEquals(this.pageSize, other.pageSize) &&
            Utils.enhancedDeepEquals(this.pit, other.pit) &&
            Utils.enhancedDeepEquals(this.resource, other.resource) &&
            Utils.enhancedDeepEquals(this.sort, other.sort);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            cursor, expand, groupBy,
            insertionDate, pageSize, pit,
            resource, sort);
    }
    
    @Override
    public String toString() {
        return Utils.toString(QueryTemplateVolumeParams.class,
                "cursor", cursor,
                "expand", expand,
                "groupBy", groupBy,
                "insertionDate", insertionDate,
                "pageSize", pageSize,
                "pit", pit,
                "resource", resource,
                "sort", sort);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<String> cursor = Optional.empty();

        private Optional<String> expand = Optional.empty();

        private Optional<Long> groupBy = Optional.empty();

        private Optional<Boolean> insertionDate = Optional.empty();

        private Optional<Long> pageSize = Optional.empty();

        private Optional<OffsetDateTime> pit = Optional.empty();

        private Optional<? extends V2QueryParamsResourceVolumes> resource = Optional.empty();

        private Optional<String> sort = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * Parameter used in pagination requests. Maximum page size is set to 15.
         * Set to the value of next for the next page of results.
         * Set to the value of previous for the previous page of results.
         * No other parameters can be set when this parameter is set.
         */
        public Builder cursor(String cursor) {
            Utils.checkNotNull(cursor, "cursor");
            this.cursor = Optional.ofNullable(cursor);
            return this;
        }

        /**
         * Parameter used in pagination requests. Maximum page size is set to 15.
         * Set to the value of next for the next page of results.
         * Set to the value of previous for the previous page of results.
         * No other parameters can be set when this parameter is set.
         */
        public Builder cursor(Optional<String> cursor) {
            Utils.checkNotNull(cursor, "cursor");
            this.cursor = cursor;
            return this;
        }


        public Builder expand(String expand) {
            Utils.checkNotNull(expand, "expand");
            this.expand = Optional.ofNullable(expand);
            return this;
        }

        public Builder expand(Optional<String> expand) {
            Utils.checkNotNull(expand, "expand");
            this.expand = expand;
            return this;
        }


        public Builder groupBy(long groupBy) {
            Utils.checkNotNull(groupBy, "groupBy");
            this.groupBy = Optional.ofNullable(groupBy);
            return this;
        }

        public Builder groupBy(Optional<Long> groupBy) {
            Utils.checkNotNull(groupBy, "groupBy");
            this.groupBy = groupBy;
            return this;
        }


        public Builder insertionDate(boolean insertionDate) {
            Utils.checkNotNull(insertionDate, "insertionDate");
            this.insertionDate = Optional.ofNullable(insertionDate);
            return this;
        }

        public Builder insertionDate(Optional<Boolean> insertionDate) {
            Utils.checkNotNull(insertionDate, "insertionDate");
            this.insertionDate = insertionDate;
            return this;
        }


        /**
         * The maximum number of results to return per page.
         */
        public Builder pageSize(long pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = Optional.ofNullable(pageSize);
            return this;
        }

        /**
         * The maximum number of results to return per page.
         */
        public Builder pageSize(Optional<Long> pageSize) {
            Utils.checkNotNull(pageSize, "pageSize");
            this.pageSize = pageSize;
            return this;
        }


        public Builder pit(OffsetDateTime pit) {
            Utils.checkNotNull(pit, "pit");
            this.pit = Optional.ofNullable(pit);
            return this;
        }

        public Builder pit(Optional<OffsetDateTime> pit) {
            Utils.checkNotNull(pit, "pit");
            this.pit = pit;
            return this;
        }


        public Builder resource(V2QueryParamsResourceVolumes resource) {
            Utils.checkNotNull(resource, "resource");
            this.resource = Optional.ofNullable(resource);
            return this;
        }

        public Builder resource(Optional<? extends V2QueryParamsResourceVolumes> resource) {
            Utils.checkNotNull(resource, "resource");
            this.resource = resource;
            return this;
        }


        /**
         * Sort results using a field name and order (ascending or descending).
         * Format: `&lt;field&gt;:&lt;order&gt;`, where `&lt;field&gt;` is the field name and `&lt;order&gt;`
         * is either `asc` or `desc`.
         */
        public Builder sort(String sort) {
            Utils.checkNotNull(sort, "sort");
            this.sort = Optional.ofNullable(sort);
            return this;
        }

        /**
         * Sort results using a field name and order (ascending or descending).
         * Format: `&lt;field&gt;:&lt;order&gt;`, where `&lt;field&gt;` is the field name and `&lt;order&gt;`
         * is either `asc` or `desc`.
         */
        public Builder sort(Optional<String> sort) {
            Utils.checkNotNull(sort, "sort");
            this.sort = sort;
            return this;
        }

        public QueryTemplateVolumeParams build() {

            return new QueryTemplateVolumeParams(
                cursor, expand, groupBy,
                insertionDate, pageSize, pit,
                resource, sort);
        }

    }
}
