/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.core.type.TypeReference;
import com.formance.formance_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;

import java.time.OffsetDateTime;
import java.time.LocalDate;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.formance.formance_sdk.utils.TypedObject;
import com.formance.formance_sdk.utils.Utils.JsonShape;


@JsonDeserialize(using = Subject._Deserializer.class)
public class Subject {

    @com.fasterxml.jackson.annotation.JsonValue
    private TypedObject value;
    
    private Subject(TypedObject value) {
        this.value = value;
    }

    public static Subject of(LedgerAccountSubject value) {
        Utils.checkNotNull(value, "value");
        return new Subject(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<LedgerAccountSubject>(){}));
    }

    public static Subject of(WalletSubject value) {
        Utils.checkNotNull(value, "value");
        return new Subject(TypedObject.of(value, JsonShape.DEFAULT, new TypeReference<WalletSubject>(){}));
    }
    
    /**
     * Returns an instance of one of these types:
     * <ul>
     * <li>{@code LedgerAccountSubject}</li>
     * <li>{@code WalletSubject}</li>
     * </ul>
     * 
     * <p>Use {@code instanceof} to determine what type is returned. For example:
     * 
     * <pre>
     * if (obj.value() instanceof String) {
     *     String answer = (String) obj.value();
     *     System.out.println("answer=" + answer);
     * }
     * </pre>
     * 
     * @return value of oneOf type
     **/ 
    public java.lang.Object value() {
        return value.value();
    }    
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Subject other = (Subject) o;
        return java.util.Objects.deepEquals(this.value.value(), other.value.value()); 
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(value.value());
    }
    
    @SuppressWarnings("serial")
    public static final class _Deserializer extends com.formance.formance_sdk.utils.OneOfDeserializer<Subject> {

        public _Deserializer() {
            super(Subject.class,
                  Utils.TypeReferenceWithShape.of(new TypeReference<LedgerAccountSubject>() {}, Utils.JsonShape.DEFAULT),
                  Utils.TypeReferenceWithShape.of(new TypeReference<WalletSubject>() {}, Utils.JsonShape.DEFAULT));
        }
    }
    
    @Override
    public String toString() {
        return Utils.toString(Subject.class,
                "value", value);
    }
 
}
