/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class V3ConnectorScheduleInstancesCursorResponse {

    @JsonProperty("cursor")
    private V3ConnectorScheduleInstancesCursorResponseCursor cursor;

    @JsonCreator
    public V3ConnectorScheduleInstancesCursorResponse(
            @JsonProperty("cursor") V3ConnectorScheduleInstancesCursorResponseCursor cursor) {
        Utils.checkNotNull(cursor, "cursor");
        this.cursor = cursor;
    }

    @JsonIgnore
    public V3ConnectorScheduleInstancesCursorResponseCursor cursor() {
        return cursor;
    }

    public static Builder builder() {
        return new Builder();
    }


    public V3ConnectorScheduleInstancesCursorResponse withCursor(V3ConnectorScheduleInstancesCursorResponseCursor cursor) {
        Utils.checkNotNull(cursor, "cursor");
        this.cursor = cursor;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3ConnectorScheduleInstancesCursorResponse other = (V3ConnectorScheduleInstancesCursorResponse) o;
        return 
            Utils.enhancedDeepEquals(this.cursor, other.cursor);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            cursor);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3ConnectorScheduleInstancesCursorResponse.class,
                "cursor", cursor);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private V3ConnectorScheduleInstancesCursorResponseCursor cursor;

        private Builder() {
          // force use of static builder() method
        }


        public Builder cursor(V3ConnectorScheduleInstancesCursorResponseCursor cursor) {
            Utils.checkNotNull(cursor, "cursor");
            this.cursor = cursor;
            return this;
        }

        public V3ConnectorScheduleInstancesCursorResponse build() {

            return new V3ConnectorScheduleInstancesCursorResponse(
                cursor);
        }

    }
}
