/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;


import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.util.List;
import java.util.Objects;


public class V3CreatePoolRequest {

    @JsonProperty("accountIDs")
    private List<String> accountIDs;

    @JsonProperty("name")
    private String name;

    @JsonCreator
    public V3CreatePoolRequest(
            @JsonProperty("accountIDs") List<String> accountIDs,
            @JsonProperty("name") String name) {
        Utils.checkNotNull(accountIDs, "accountIDs");
        Utils.checkNotNull(name, "name");
        this.accountIDs = accountIDs;
        this.name = name;
    }

    @JsonIgnore
    public List<String> accountIDs() {
        return accountIDs;
    }

    @JsonIgnore
    public String name() {
        return name;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public V3CreatePoolRequest withAccountIDs(List<String> accountIDs) {
        Utils.checkNotNull(accountIDs, "accountIDs");
        this.accountIDs = accountIDs;
        return this;
    }

    public V3CreatePoolRequest withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3CreatePoolRequest other = (V3CreatePoolRequest) o;
        return 
            Objects.deepEquals(this.accountIDs, other.accountIDs) &&
            Objects.deepEquals(this.name, other.name);
    }
    
    @Override
    public int hashCode() {
        return Objects.hash(
            accountIDs,
            name);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3CreatePoolRequest.class,
                "accountIDs", accountIDs,
                "name", name);
    }
    
    public final static class Builder {
 
        private List<String> accountIDs;
 
        private String name;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder accountIDs(List<String> accountIDs) {
            Utils.checkNotNull(accountIDs, "accountIDs");
            this.accountIDs = accountIDs;
            return this;
        }

        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }
        
        public V3CreatePoolRequest build() {
            return new V3CreatePoolRequest(
                accountIDs,
                name);
        }
    }
}

