/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Object;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;


public class V3Pool {

    @JsonProperty("createdAt")
    private OffsetDateTime createdAt;


    @JsonProperty("id")
    private String id;


    @JsonProperty("name")
    private String name;


    @JsonProperty("poolAccounts")
    private List<String> poolAccounts;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("query")
    private Optional<? extends Map<String, Object>> query;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("type")
    private Optional<? extends V3PoolTypeEnum> type;

    @JsonCreator
    public V3Pool(
            @JsonProperty("createdAt") OffsetDateTime createdAt,
            @JsonProperty("id") String id,
            @JsonProperty("name") String name,
            @JsonProperty("poolAccounts") List<String> poolAccounts,
            @JsonProperty("query") Optional<? extends Map<String, Object>> query,
            @JsonProperty("type") Optional<? extends V3PoolTypeEnum> type) {
        Utils.checkNotNull(createdAt, "createdAt");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(name, "name");
        Utils.checkNotNull(poolAccounts, "poolAccounts");
        Utils.checkNotNull(query, "query");
        Utils.checkNotNull(type, "type");
        this.createdAt = createdAt;
        this.id = id;
        this.name = name;
        this.poolAccounts = poolAccounts;
        this.query = query;
        this.type = type;
    }
    
    public V3Pool(
            OffsetDateTime createdAt,
            String id,
            String name,
            List<String> poolAccounts) {
        this(createdAt, id, name,
            poolAccounts, Optional.empty(), Optional.empty());
    }

    @JsonIgnore
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    @JsonIgnore
    public String id() {
        return id;
    }

    @JsonIgnore
    public String name() {
        return name;
    }

    @JsonIgnore
    public List<String> poolAccounts() {
        return poolAccounts;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, Object>> query() {
        return (Optional<Map<String, Object>>) query;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<V3PoolTypeEnum> type() {
        return (Optional<V3PoolTypeEnum>) type;
    }

    public static Builder builder() {
        return new Builder();
    }


    public V3Pool withCreatedAt(OffsetDateTime createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = createdAt;
        return this;
    }

    public V3Pool withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public V3Pool withName(String name) {
        Utils.checkNotNull(name, "name");
        this.name = name;
        return this;
    }

    public V3Pool withPoolAccounts(List<String> poolAccounts) {
        Utils.checkNotNull(poolAccounts, "poolAccounts");
        this.poolAccounts = poolAccounts;
        return this;
    }

    public V3Pool withQuery(Map<String, Object> query) {
        Utils.checkNotNull(query, "query");
        this.query = Optional.ofNullable(query);
        return this;
    }


    public V3Pool withQuery(Optional<? extends Map<String, Object>> query) {
        Utils.checkNotNull(query, "query");
        this.query = query;
        return this;
    }

    public V3Pool withType(V3PoolTypeEnum type) {
        Utils.checkNotNull(type, "type");
        this.type = Optional.ofNullable(type);
        return this;
    }


    public V3Pool withType(Optional<? extends V3PoolTypeEnum> type) {
        Utils.checkNotNull(type, "type");
        this.type = type;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3Pool other = (V3Pool) o;
        return 
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.name, other.name) &&
            Utils.enhancedDeepEquals(this.poolAccounts, other.poolAccounts) &&
            Utils.enhancedDeepEquals(this.query, other.query) &&
            Utils.enhancedDeepEquals(this.type, other.type);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            createdAt, id, name,
            poolAccounts, query, type);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3Pool.class,
                "createdAt", createdAt,
                "id", id,
                "name", name,
                "poolAccounts", poolAccounts,
                "query", query,
                "type", type);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private OffsetDateTime createdAt;

        private String id;

        private String name;

        private List<String> poolAccounts;

        private Optional<? extends Map<String, Object>> query = Optional.empty();

        private Optional<? extends V3PoolTypeEnum> type = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder createdAt(OffsetDateTime createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = createdAt;
            return this;
        }


        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder name(String name) {
            Utils.checkNotNull(name, "name");
            this.name = name;
            return this;
        }


        public Builder poolAccounts(List<String> poolAccounts) {
            Utils.checkNotNull(poolAccounts, "poolAccounts");
            this.poolAccounts = poolAccounts;
            return this;
        }


        public Builder query(Map<String, Object> query) {
            Utils.checkNotNull(query, "query");
            this.query = Optional.ofNullable(query);
            return this;
        }

        public Builder query(Optional<? extends Map<String, Object>> query) {
            Utils.checkNotNull(query, "query");
            this.query = query;
            return this;
        }


        public Builder type(V3PoolTypeEnum type) {
            Utils.checkNotNull(type, "type");
            this.type = Optional.ofNullable(type);
            return this;
        }

        public Builder type(Optional<? extends V3PoolTypeEnum> type) {
            Utils.checkNotNull(type, "type");
            this.type = type;
            return this;
        }

        public V3Pool build() {

            return new V3Pool(
                createdAt, id, name,
                poolAccounts, query, type);
        }

    }
}
