/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */


package com.formance.formance_sdk.models.shared;
import com.fasterxml.jackson.annotation.JsonValue;
import java.lang.String;
import java.util.Objects;
import java.util.Optional;
public enum WebhooksErrorsEnum {
    INTERNAL("INTERNAL"),
    VALIDATION("VALIDATION"),
    NOT_FOUND("NOT_FOUND");

    @JsonValue
    private final String value;

    private WebhooksErrorsEnum(String value) {
        this.value = value;
    }
    
    public String value() {
        return value;
    }
    
    public static Optional<WebhooksErrorsEnum> fromValue(String value) {
        for (WebhooksErrorsEnum o: WebhooksErrorsEnum.values()) {
            if (Objects.deepEquals(o.value, value)) {
                return Optional.of(o);
            }
        }
        return Optional.empty();
    }
}
