/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.SpeakeasyMetadata;


public class V2GetInstanceStageHistoryRequest {
    /**
     * The instance id
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=instanceID")
    public String instanceID;

    public V2GetInstanceStageHistoryRequest withInstanceID(String instanceID) {
        this.instanceID = instanceID;
        return this;
    }
    
    /**
     * The stage number
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=number")
    public Long number;

    public V2GetInstanceStageHistoryRequest withNumber(Long number) {
        this.number = number;
        return this;
    }
    
    public V2GetInstanceStageHistoryRequest(@JsonProperty("instanceID") String instanceID, @JsonProperty("number") Long number) {
        this.instanceID = instanceID;
        this.number = number;
  }
}
