/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.orchestration;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.util.Optional;


public class V2ActivityDebitWallet {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("data")
    private Optional<? extends V2DebitWalletRequest> v2DebitWalletRequest;


    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("id")
    private Optional<String> id;

    @JsonCreator
    public V2ActivityDebitWallet(
            @JsonProperty("data") Optional<? extends V2DebitWalletRequest> v2DebitWalletRequest,
            @JsonProperty("id") Optional<String> id) {
        Utils.checkNotNull(v2DebitWalletRequest, "v2DebitWalletRequest");
        Utils.checkNotNull(id, "id");
        this.v2DebitWalletRequest = v2DebitWalletRequest;
        this.id = id;
    }
    
    public V2ActivityDebitWallet() {
        this(Optional.empty(), Optional.empty());
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<V2DebitWalletRequest> v2DebitWalletRequest() {
        return (Optional<V2DebitWalletRequest>) v2DebitWalletRequest;
    }

    @JsonIgnore
    public Optional<String> id() {
        return id;
    }

    public static Builder builder() {
        return new Builder();
    }


    public V2ActivityDebitWallet withV2DebitWalletRequest(V2DebitWalletRequest v2DebitWalletRequest) {
        Utils.checkNotNull(v2DebitWalletRequest, "v2DebitWalletRequest");
        this.v2DebitWalletRequest = Optional.ofNullable(v2DebitWalletRequest);
        return this;
    }


    public V2ActivityDebitWallet withV2DebitWalletRequest(Optional<? extends V2DebitWalletRequest> v2DebitWalletRequest) {
        Utils.checkNotNull(v2DebitWalletRequest, "v2DebitWalletRequest");
        this.v2DebitWalletRequest = v2DebitWalletRequest;
        return this;
    }

    public V2ActivityDebitWallet withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = Optional.ofNullable(id);
        return this;
    }


    public V2ActivityDebitWallet withId(Optional<String> id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V2ActivityDebitWallet other = (V2ActivityDebitWallet) o;
        return 
            Utils.enhancedDeepEquals(this.v2DebitWalletRequest, other.v2DebitWalletRequest) &&
            Utils.enhancedDeepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            v2DebitWalletRequest, id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V2ActivityDebitWallet.class,
                "v2DebitWalletRequest", v2DebitWalletRequest,
                "id", id);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends V2DebitWalletRequest> v2DebitWalletRequest = Optional.empty();

        private Optional<String> id = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        public Builder v2DebitWalletRequest(V2DebitWalletRequest v2DebitWalletRequest) {
            Utils.checkNotNull(v2DebitWalletRequest, "v2DebitWalletRequest");
            this.v2DebitWalletRequest = Optional.ofNullable(v2DebitWalletRequest);
            return this;
        }

        public Builder v2DebitWalletRequest(Optional<? extends V2DebitWalletRequest> v2DebitWalletRequest) {
            Utils.checkNotNull(v2DebitWalletRequest, "v2DebitWalletRequest");
            this.v2DebitWalletRequest = v2DebitWalletRequest;
            return this;
        }


        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = Optional.ofNullable(id);
            return this;
        }

        public Builder id(Optional<String> id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }

        public V2ActivityDebitWallet build() {

            return new V2ActivityDebitWallet(
                v2DebitWalletRequest, id);
        }

    }
}
