workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: $openapi_spec_url
        registry:
            location: registry.speakeasyapi.dev/formance/formance/formance-sdk-java
targets:
    Java:
        target: java
        source: formance-sdk-java
        publish:
            java:
                ossrhUsername: $OSSRH_USERNAME
                ossrhPassword: $OSSRH_PASSWORD
                gpgSecretKey: $JAVA_GPG_SECRET_KEY
                gpgPassPhrase: $JAVA_GPG_PASSPHRASE
        codeSamples:
            output: formance-sdk-java.yaml
            registry:
                location: registry.speakeasyapi.dev/formance/formance/formance-sdk-java
