workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: $openapi_spec_url
        registry:
            location: registry.speakeasyapi.dev/formance/formance/my-source
targets:
    Java:
        target: java
        source: my-source
        publish:
            java:
                ossrhUsername: $OSSRH_USERNAME
                ossrhPassword: $OSSRH_PASSWORD
                gpgSecretKey: $JAVA_GPG_SECRET_KEY
                gpgPassPhrase: $JAVA_GPG_PASSPHRASE
                useSonatypeLegacy: true
