workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    stacks-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v3.0.0/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/stacks-source
targets:
    Java:
        target: java
        source: stacks-source
        publish:
            java:
                ossrhUsername: $OSSRH_USERNAME
                ossrhPassword: $OSSRH_PASSWORD
                gpgSecretKey: $JAVA_GPG_SECRET_KEY
                gpgPassPhrase: $JAVA_GPG_PASSPHRASE
                useSonatypeLegacy: true