workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    my-source:
        inputs:
            - location: https://github.com/formancehq/stack/releases/download/v2.1.1/generate.json
        registry:
            location: registry.speakeasyapi.dev/formance/formance/my-source
targets:
    Java:
        target: java
        source: my-source
        publish:
            java:
                ossrhUsername: $OSSRH_USERNAME
                ossrhPassword: $OSSRH_PASSWORD
                gpgSecretKey: $JAVA_GPG_SECRET_KEY
                gpgPassPhrase: $JAVA_GPG_PASSPHRASE
                useSonatypeLegacy: true
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/formance/formance/my-source-code-samples
            blocking: false
