/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.payments;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.math.BigInteger;
import java.time.OffsetDateTime;
import java.util.List;
import java.util.Map;
import java.util.Optional;


public class Payment {

    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("provider")
    private Optional<? extends Connector> connector;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("metadata")
    private Optional<? extends Map<String, String>> paymentMetadata;


    @JsonProperty("scheme")
    private PaymentScheme paymentScheme;


    @JsonProperty("status")
    private PaymentStatus paymentStatus;


    @JsonProperty("type")
    private PaymentType paymentType;


    @JsonProperty("adjustments")
    private List<PaymentAdjustment> adjustments;


    @JsonProperty("amount")
    private BigInteger amount;


    @JsonProperty("asset")
    private String asset;


    @JsonProperty("connectorID")
    private String connectorID;


    @JsonProperty("createdAt")
    private OffsetDateTime createdAt;


    @JsonProperty("destinationAccountID")
    private String destinationAccountID;


    @JsonProperty("id")
    private String id;


    @JsonProperty("initialAmount")
    private BigInteger initialAmount;


    @JsonInclude(Include.ALWAYS)
    @JsonProperty("raw")
    private Optional<? extends PaymentRaw> raw;


    @JsonProperty("reference")
    private String reference;


    @JsonProperty("sourceAccountID")
    private String sourceAccountID;

    @JsonCreator
    public Payment(
            @JsonProperty("provider") Optional<? extends Connector> connector,
            @JsonProperty("metadata") Optional<? extends Map<String, String>> paymentMetadata,
            @JsonProperty("scheme") PaymentScheme paymentScheme,
            @JsonProperty("status") PaymentStatus paymentStatus,
            @JsonProperty("type") PaymentType paymentType,
            @JsonProperty("adjustments") List<PaymentAdjustment> adjustments,
            @JsonProperty("amount") BigInteger amount,
            @JsonProperty("asset") String asset,
            @JsonProperty("connectorID") String connectorID,
            @JsonProperty("createdAt") OffsetDateTime createdAt,
            @JsonProperty("destinationAccountID") String destinationAccountID,
            @JsonProperty("id") String id,
            @JsonProperty("initialAmount") BigInteger initialAmount,
            @JsonProperty("raw") Optional<? extends PaymentRaw> raw,
            @JsonProperty("reference") String reference,
            @JsonProperty("sourceAccountID") String sourceAccountID) {
        Utils.checkNotNull(connector, "connector");
        Utils.checkNotNull(paymentMetadata, "paymentMetadata");
        Utils.checkNotNull(paymentScheme, "paymentScheme");
        Utils.checkNotNull(paymentStatus, "paymentStatus");
        Utils.checkNotNull(paymentType, "paymentType");
        Utils.checkNotNull(adjustments, "adjustments");
        Utils.checkNotNull(amount, "amount");
        Utils.checkNotNull(asset, "asset");
        Utils.checkNotNull(connectorID, "connectorID");
        Utils.checkNotNull(createdAt, "createdAt");
        Utils.checkNotNull(destinationAccountID, "destinationAccountID");
        Utils.checkNotNull(id, "id");
        Utils.checkNotNull(initialAmount, "initialAmount");
        Utils.checkNotNull(raw, "raw");
        Utils.checkNotNull(reference, "reference");
        Utils.checkNotNull(sourceAccountID, "sourceAccountID");
        this.connector = connector;
        this.paymentMetadata = paymentMetadata;
        this.paymentScheme = paymentScheme;
        this.paymentStatus = paymentStatus;
        this.paymentType = paymentType;
        this.adjustments = adjustments;
        this.amount = amount;
        this.asset = asset;
        this.connectorID = connectorID;
        this.createdAt = createdAt;
        this.destinationAccountID = destinationAccountID;
        this.id = id;
        this.initialAmount = initialAmount;
        this.raw = raw;
        this.reference = reference;
        this.sourceAccountID = sourceAccountID;
    }
    
    public Payment(
            PaymentScheme paymentScheme,
            PaymentStatus paymentStatus,
            PaymentType paymentType,
            List<PaymentAdjustment> adjustments,
            BigInteger amount,
            String asset,
            String connectorID,
            OffsetDateTime createdAt,
            String destinationAccountID,
            String id,
            BigInteger initialAmount,
            String reference,
            String sourceAccountID) {
        this(Optional.empty(), Optional.empty(), paymentScheme,
            paymentStatus, paymentType, adjustments,
            amount, asset, connectorID,
            createdAt, destinationAccountID, id,
            initialAmount, Optional.empty(), reference,
            sourceAccountID);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Connector> connector() {
        return (Optional<Connector>) connector;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<Map<String, String>> paymentMetadata() {
        return (Optional<Map<String, String>>) paymentMetadata;
    }

    @JsonIgnore
    public PaymentScheme paymentScheme() {
        return paymentScheme;
    }

    @JsonIgnore
    public PaymentStatus paymentStatus() {
        return paymentStatus;
    }

    @JsonIgnore
    public PaymentType paymentType() {
        return paymentType;
    }

    @JsonIgnore
    public List<PaymentAdjustment> adjustments() {
        return adjustments;
    }

    @JsonIgnore
    public BigInteger amount() {
        return amount;
    }

    @JsonIgnore
    public String asset() {
        return asset;
    }

    @JsonIgnore
    public String connectorID() {
        return connectorID;
    }

    @JsonIgnore
    public OffsetDateTime createdAt() {
        return createdAt;
    }

    @JsonIgnore
    public String destinationAccountID() {
        return destinationAccountID;
    }

    @JsonIgnore
    public String id() {
        return id;
    }

    @JsonIgnore
    public BigInteger initialAmount() {
        return initialAmount;
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<PaymentRaw> raw() {
        return (Optional<PaymentRaw>) raw;
    }

    @JsonIgnore
    public String reference() {
        return reference;
    }

    @JsonIgnore
    public String sourceAccountID() {
        return sourceAccountID;
    }

    public static Builder builder() {
        return new Builder();
    }


    public Payment withConnector(Connector connector) {
        Utils.checkNotNull(connector, "connector");
        this.connector = Optional.ofNullable(connector);
        return this;
    }


    public Payment withConnector(Optional<? extends Connector> connector) {
        Utils.checkNotNull(connector, "connector");
        this.connector = connector;
        return this;
    }

    public Payment withPaymentMetadata(Map<String, String> paymentMetadata) {
        Utils.checkNotNull(paymentMetadata, "paymentMetadata");
        this.paymentMetadata = Optional.ofNullable(paymentMetadata);
        return this;
    }


    public Payment withPaymentMetadata(Optional<? extends Map<String, String>> paymentMetadata) {
        Utils.checkNotNull(paymentMetadata, "paymentMetadata");
        this.paymentMetadata = paymentMetadata;
        return this;
    }

    public Payment withPaymentScheme(PaymentScheme paymentScheme) {
        Utils.checkNotNull(paymentScheme, "paymentScheme");
        this.paymentScheme = paymentScheme;
        return this;
    }

    public Payment withPaymentStatus(PaymentStatus paymentStatus) {
        Utils.checkNotNull(paymentStatus, "paymentStatus");
        this.paymentStatus = paymentStatus;
        return this;
    }

    public Payment withPaymentType(PaymentType paymentType) {
        Utils.checkNotNull(paymentType, "paymentType");
        this.paymentType = paymentType;
        return this;
    }

    public Payment withAdjustments(List<PaymentAdjustment> adjustments) {
        Utils.checkNotNull(adjustments, "adjustments");
        this.adjustments = adjustments;
        return this;
    }

    public Payment withAmount(long amount) {
        this.amount = BigInteger.valueOf(amount);
        return this;
    }

    public Payment withAmount(BigInteger amount) {
        Utils.checkNotNull(amount, "amount");
        this.amount = amount;
        return this;
    }

    public Payment withAsset(String asset) {
        Utils.checkNotNull(asset, "asset");
        this.asset = asset;
        return this;
    }

    public Payment withConnectorID(String connectorID) {
        Utils.checkNotNull(connectorID, "connectorID");
        this.connectorID = connectorID;
        return this;
    }

    public Payment withCreatedAt(OffsetDateTime createdAt) {
        Utils.checkNotNull(createdAt, "createdAt");
        this.createdAt = createdAt;
        return this;
    }

    public Payment withDestinationAccountID(String destinationAccountID) {
        Utils.checkNotNull(destinationAccountID, "destinationAccountID");
        this.destinationAccountID = destinationAccountID;
        return this;
    }

    public Payment withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }

    public Payment withInitialAmount(long initialAmount) {
        this.initialAmount = BigInteger.valueOf(initialAmount);
        return this;
    }

    public Payment withInitialAmount(BigInteger initialAmount) {
        Utils.checkNotNull(initialAmount, "initialAmount");
        this.initialAmount = initialAmount;
        return this;
    }

    public Payment withRaw(PaymentRaw raw) {
        Utils.checkNotNull(raw, "raw");
        this.raw = Optional.ofNullable(raw);
        return this;
    }


    public Payment withRaw(Optional<? extends PaymentRaw> raw) {
        Utils.checkNotNull(raw, "raw");
        this.raw = raw;
        return this;
    }

    public Payment withReference(String reference) {
        Utils.checkNotNull(reference, "reference");
        this.reference = reference;
        return this;
    }

    public Payment withSourceAccountID(String sourceAccountID) {
        Utils.checkNotNull(sourceAccountID, "sourceAccountID");
        this.sourceAccountID = sourceAccountID;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        Payment other = (Payment) o;
        return 
            Utils.enhancedDeepEquals(this.connector, other.connector) &&
            Utils.enhancedDeepEquals(this.paymentMetadata, other.paymentMetadata) &&
            Utils.enhancedDeepEquals(this.paymentScheme, other.paymentScheme) &&
            Utils.enhancedDeepEquals(this.paymentStatus, other.paymentStatus) &&
            Utils.enhancedDeepEquals(this.paymentType, other.paymentType) &&
            Utils.enhancedDeepEquals(this.adjustments, other.adjustments) &&
            Utils.enhancedDeepEquals(this.amount, other.amount) &&
            Utils.enhancedDeepEquals(this.asset, other.asset) &&
            Utils.enhancedDeepEquals(this.connectorID, other.connectorID) &&
            Utils.enhancedDeepEquals(this.createdAt, other.createdAt) &&
            Utils.enhancedDeepEquals(this.destinationAccountID, other.destinationAccountID) &&
            Utils.enhancedDeepEquals(this.id, other.id) &&
            Utils.enhancedDeepEquals(this.initialAmount, other.initialAmount) &&
            Utils.enhancedDeepEquals(this.raw, other.raw) &&
            Utils.enhancedDeepEquals(this.reference, other.reference) &&
            Utils.enhancedDeepEquals(this.sourceAccountID, other.sourceAccountID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            connector, paymentMetadata, paymentScheme,
            paymentStatus, paymentType, adjustments,
            amount, asset, connectorID,
            createdAt, destinationAccountID, id,
            initialAmount, raw, reference,
            sourceAccountID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(Payment.class,
                "connector", connector,
                "paymentMetadata", paymentMetadata,
                "paymentScheme", paymentScheme,
                "paymentStatus", paymentStatus,
                "paymentType", paymentType,
                "adjustments", adjustments,
                "amount", amount,
                "asset", asset,
                "connectorID", connectorID,
                "createdAt", createdAt,
                "destinationAccountID", destinationAccountID,
                "id", id,
                "initialAmount", initialAmount,
                "raw", raw,
                "reference", reference,
                "sourceAccountID", sourceAccountID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private Optional<? extends Connector> connector = Optional.empty();

        private Optional<? extends Map<String, String>> paymentMetadata = Optional.empty();

        private PaymentScheme paymentScheme;

        private PaymentStatus paymentStatus;

        private PaymentType paymentType;

        private List<PaymentAdjustment> adjustments;

        private BigInteger amount;

        private String asset;

        private String connectorID;

        private OffsetDateTime createdAt;

        private String destinationAccountID;

        private String id;

        private BigInteger initialAmount;

        private Optional<? extends PaymentRaw> raw = Optional.empty();

        private String reference;

        private String sourceAccountID;

        private Builder() {
          // force use of static builder() method
        }


        public Builder connector(Connector connector) {
            Utils.checkNotNull(connector, "connector");
            this.connector = Optional.ofNullable(connector);
            return this;
        }

        public Builder connector(Optional<? extends Connector> connector) {
            Utils.checkNotNull(connector, "connector");
            this.connector = connector;
            return this;
        }


        public Builder paymentMetadata(Map<String, String> paymentMetadata) {
            Utils.checkNotNull(paymentMetadata, "paymentMetadata");
            this.paymentMetadata = Optional.ofNullable(paymentMetadata);
            return this;
        }

        public Builder paymentMetadata(Optional<? extends Map<String, String>> paymentMetadata) {
            Utils.checkNotNull(paymentMetadata, "paymentMetadata");
            this.paymentMetadata = paymentMetadata;
            return this;
        }


        public Builder paymentScheme(PaymentScheme paymentScheme) {
            Utils.checkNotNull(paymentScheme, "paymentScheme");
            this.paymentScheme = paymentScheme;
            return this;
        }


        public Builder paymentStatus(PaymentStatus paymentStatus) {
            Utils.checkNotNull(paymentStatus, "paymentStatus");
            this.paymentStatus = paymentStatus;
            return this;
        }


        public Builder paymentType(PaymentType paymentType) {
            Utils.checkNotNull(paymentType, "paymentType");
            this.paymentType = paymentType;
            return this;
        }


        public Builder adjustments(List<PaymentAdjustment> adjustments) {
            Utils.checkNotNull(adjustments, "adjustments");
            this.adjustments = adjustments;
            return this;
        }


        public Builder amount(long amount) {
            this.amount = BigInteger.valueOf(amount);
            return this;
        }

        public Builder amount(BigInteger amount) {
            Utils.checkNotNull(amount, "amount");
            this.amount = amount;
            return this;
        }


        public Builder asset(String asset) {
            Utils.checkNotNull(asset, "asset");
            this.asset = asset;
            return this;
        }


        public Builder connectorID(String connectorID) {
            Utils.checkNotNull(connectorID, "connectorID");
            this.connectorID = connectorID;
            return this;
        }


        public Builder createdAt(OffsetDateTime createdAt) {
            Utils.checkNotNull(createdAt, "createdAt");
            this.createdAt = createdAt;
            return this;
        }


        public Builder destinationAccountID(String destinationAccountID) {
            Utils.checkNotNull(destinationAccountID, "destinationAccountID");
            this.destinationAccountID = destinationAccountID;
            return this;
        }


        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }


        public Builder initialAmount(long initialAmount) {
            this.initialAmount = BigInteger.valueOf(initialAmount);
            return this;
        }

        public Builder initialAmount(BigInteger initialAmount) {
            Utils.checkNotNull(initialAmount, "initialAmount");
            this.initialAmount = initialAmount;
            return this;
        }


        public Builder raw(PaymentRaw raw) {
            Utils.checkNotNull(raw, "raw");
            this.raw = Optional.ofNullable(raw);
            return this;
        }

        public Builder raw(Optional<? extends PaymentRaw> raw) {
            Utils.checkNotNull(raw, "raw");
            this.raw = raw;
            return this;
        }


        public Builder reference(String reference) {
            Utils.checkNotNull(reference, "reference");
            this.reference = reference;
            return this;
        }


        public Builder sourceAccountID(String sourceAccountID) {
            Utils.checkNotNull(sourceAccountID, "sourceAccountID");
            this.sourceAccountID = sourceAccountID;
            return this;
        }

        public Payment build() {

            return new Payment(
                connector, paymentMetadata, paymentScheme,
                paymentStatus, paymentType, adjustments,
                amount, asset, connectorID,
                createdAt, destinationAccountID, id,
                initialAmount, raw, reference,
                sourceAccountID);
        }

    }
}
