/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.payments;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;

/**
 * TransferInitiationsCursor
 * 
 * <p>OK
 */
public class TransferInitiationsCursor {

    @JsonProperty("cursor")
    private TransferInitiationsCursorCursorBase cursorBase;

    @JsonCreator
    public TransferInitiationsCursor(
            @JsonProperty("cursor") TransferInitiationsCursorCursorBase cursorBase) {
        Utils.checkNotNull(cursorBase, "cursorBase");
        this.cursorBase = cursorBase;
    }

    @JsonIgnore
    public TransferInitiationsCursorCursorBase cursorBase() {
        return cursorBase;
    }

    public static Builder builder() {
        return new Builder();
    }


    public TransferInitiationsCursor withCursorBase(TransferInitiationsCursorCursorBase cursorBase) {
        Utils.checkNotNull(cursorBase, "cursorBase");
        this.cursorBase = cursorBase;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        TransferInitiationsCursor other = (TransferInitiationsCursor) o;
        return 
            Utils.enhancedDeepEquals(this.cursorBase, other.cursorBase);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            cursorBase);
    }
    
    @Override
    public String toString() {
        return Utils.toString(TransferInitiationsCursor.class,
                "cursorBase", cursorBase);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private TransferInitiationsCursorCursorBase cursorBase;

        private Builder() {
          // force use of static builder() method
        }


        public Builder cursorBase(TransferInitiationsCursorCursorBase cursorBase) {
            Utils.checkNotNull(cursorBase, "cursorBase");
            this.cursorBase = cursorBase;
            return this;
        }

        public TransferInitiationsCursor build() {

            return new TransferInitiationsCursor(
                cursorBase);
        }

    }
}
