/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.payments;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class V3CreatePaymentResponse {

    @JsonProperty("data")
    private V3Payment v3Payment;

    @JsonCreator
    public V3CreatePaymentResponse(
            @JsonProperty("data") V3Payment v3Payment) {
        Utils.checkNotNull(v3Payment, "v3Payment");
        this.v3Payment = v3Payment;
    }

    @JsonIgnore
    public V3Payment v3Payment() {
        return v3Payment;
    }

    public static Builder builder() {
        return new Builder();
    }


    public V3CreatePaymentResponse withV3Payment(V3Payment v3Payment) {
        Utils.checkNotNull(v3Payment, "v3Payment");
        this.v3Payment = v3Payment;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3CreatePaymentResponse other = (V3CreatePaymentResponse) o;
        return 
            Utils.enhancedDeepEquals(this.v3Payment, other.v3Payment);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            v3Payment);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3CreatePaymentResponse.class,
                "v3Payment", v3Payment);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private V3Payment v3Payment;

        private Builder() {
          // force use of static builder() method
        }


        public Builder v3Payment(V3Payment v3Payment) {
            Utils.checkNotNull(v3Payment, "v3Payment");
            this.v3Payment = v3Payment;
            return this;
        }

        public V3CreatePaymentResponse build() {

            return new V3CreatePaymentResponse(
                v3Payment);
        }

    }
}
