/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.models.shared.TransferInitiationRequest;
import com.formance.formance_sdk.operations.CreateTransferInitiation;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Exception;

public class CreateTransferInitiationRequestBuilder {

    private TransferInitiationRequest request;
    private final SDKConfiguration sdkConfiguration;

    public CreateTransferInitiationRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public CreateTransferInitiationRequestBuilder request(TransferInitiationRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public CreateTransferInitiationResponse call() throws Exception {
        
        RequestOperation<TransferInitiationRequest, CreateTransferInitiationResponse> operation
              = new CreateTransferInitiation.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
