/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.formance.formance_sdk.utils.SpeakeasyMetadata;
import com.formance.formance_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;
import java.util.Optional;


public class CreditWalletRequest {

    @SpeakeasyMetadata("request:mediaType=application/json")
    private Optional<? extends com.formance.formance_sdk.models.shared.CreditWalletRequest> creditWalletRequest;

    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=id")
    private String id;

    @JsonCreator
    public CreditWalletRequest(
            Optional<? extends com.formance.formance_sdk.models.shared.CreditWalletRequest> creditWalletRequest,
            String id) {
        Utils.checkNotNull(creditWalletRequest, "creditWalletRequest");
        Utils.checkNotNull(id, "id");
        this.creditWalletRequest = creditWalletRequest;
        this.id = id;
    }
    
    public CreditWalletRequest(
            String id) {
        this(Optional.empty(), id);
    }

    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<com.formance.formance_sdk.models.shared.CreditWalletRequest> creditWalletRequest() {
        return (Optional<com.formance.formance_sdk.models.shared.CreditWalletRequest>) creditWalletRequest;
    }

    @JsonIgnore
    public String id() {
        return id;
    }

    public final static Builder builder() {
        return new Builder();
    }

    public CreditWalletRequest withCreditWalletRequest(com.formance.formance_sdk.models.shared.CreditWalletRequest creditWalletRequest) {
        Utils.checkNotNull(creditWalletRequest, "creditWalletRequest");
        this.creditWalletRequest = Optional.ofNullable(creditWalletRequest);
        return this;
    }

    public CreditWalletRequest withCreditWalletRequest(Optional<? extends com.formance.formance_sdk.models.shared.CreditWalletRequest> creditWalletRequest) {
        Utils.checkNotNull(creditWalletRequest, "creditWalletRequest");
        this.creditWalletRequest = creditWalletRequest;
        return this;
    }

    public CreditWalletRequest withId(String id) {
        Utils.checkNotNull(id, "id");
        this.id = id;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        CreditWalletRequest other = (CreditWalletRequest) o;
        return 
            java.util.Objects.deepEquals(this.creditWalletRequest, other.creditWalletRequest) &&
            java.util.Objects.deepEquals(this.id, other.id);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            creditWalletRequest,
            id);
    }
    
    @Override
    public String toString() {
        return Utils.toString(CreditWalletRequest.class,
                "creditWalletRequest", creditWalletRequest,
                "id", id);
    }
    
    public final static class Builder {
 
        private Optional<? extends com.formance.formance_sdk.models.shared.CreditWalletRequest> creditWalletRequest = Optional.empty();
 
        private String id;  
        
        private Builder() {
          // force use of static builder() method
        }

        public Builder creditWalletRequest(com.formance.formance_sdk.models.shared.CreditWalletRequest creditWalletRequest) {
            Utils.checkNotNull(creditWalletRequest, "creditWalletRequest");
            this.creditWalletRequest = Optional.ofNullable(creditWalletRequest);
            return this;
        }

        public Builder creditWalletRequest(Optional<? extends com.formance.formance_sdk.models.shared.CreditWalletRequest> creditWalletRequest) {
            Utils.checkNotNull(creditWalletRequest, "creditWalletRequest");
            this.creditWalletRequest = creditWalletRequest;
            return this;
        }

        public Builder id(String id) {
            Utils.checkNotNull(id, "id");
            this.id = id;
            return this;
        }
        
        public CreditWalletRequest build() {
            return new CreditWalletRequest(
                creditWalletRequest,
                id);
        }
    }
}

