/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.DeleteSecret;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Exception;

public class DeleteSecretRequestBuilder {

    private DeleteSecretRequest request;
    private final SDKConfiguration sdkConfiguration;

    public DeleteSecretRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public DeleteSecretRequestBuilder request(DeleteSecretRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public DeleteSecretResponse call() throws Exception {
        
        RequestOperation<DeleteSecretRequest, DeleteSecretResponse> operation
              = new DeleteSecret.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
