/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.ForwardBankAccount;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Exception;

public class ForwardBankAccountRequestBuilder {

    private ForwardBankAccountRequest request;
    private final SDKConfiguration sdkConfiguration;

    public ForwardBankAccountRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public ForwardBankAccountRequestBuilder request(ForwardBankAccountRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public ForwardBankAccountResponse call() throws Exception {
        
        RequestOperation<ForwardBankAccountRequest, ForwardBankAccountResponse> operation
              = new ForwardBankAccount.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
