/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestlessOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.GetServerInfoPayments;
import com.formance.formance_sdk.utils.Headers;

public class GetServerInfoPaymentsRequestBuilder {

    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public GetServerInfoPaymentsRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetServerInfoPaymentsResponse call() {
        
        RequestlessOperation<GetServerInfoPaymentsResponse> operation
            = new GetServerInfoPayments.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest());
    }
}
