/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.utils.Utils;

public class GetTransactionsRequestBuilder {

    private GetTransactionsRequest request;
    private final SDKMethodInterfaces.MethodCallGetTransactions sdk;

    public GetTransactionsRequestBuilder(SDKMethodInterfaces.MethodCallGetTransactions sdk) {
        this.sdk = sdk;
    }

    public GetTransactionsRequestBuilder request(GetTransactionsRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetTransactionsResponse call() throws Exception {

        return sdk.getTransactions(
            request);
    }
}
