/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.fasterxml.jackson.core.type.TypeReference;
import com.formance.formance_sdk.utils.SpeakeasyMetadata;
import com.formance.formance_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Deprecated;
import java.math.BigDecimal;
import java.math.BigInteger;


public class GetTransactionRequest {

    /**
     * Name of the ledger.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=ledger")
    private String ledger;

    /**
     * Transaction ID.
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=txid")
    private BigInteger txid;

    @JsonCreator
    public GetTransactionRequest(
            String ledger,
            BigInteger txid) {
        Utils.checkNotNull(ledger, "ledger");
        Utils.checkNotNull(txid, "txid");
        this.ledger = ledger;
        this.txid = txid;
    }

    /**
     * Name of the ledger.
     */
    @JsonIgnore
    public String ledger() {
        return ledger;
    }

    /**
     * Transaction ID.
     */
    @JsonIgnore
    public BigInteger txid() {
        return txid;
    }

    public final static Builder builder() {
        return new Builder();
    }

    /**
     * Name of the ledger.
     */
    public GetTransactionRequest withLedger(String ledger) {
        Utils.checkNotNull(ledger, "ledger");
        this.ledger = ledger;
        return this;
    }

        /**
         * Transaction ID.
         */
    public GetTransactionRequest withTxid(long txid) {
        this.txid = BigInteger.valueOf(txid);
        return this;
    }

    /**
     * Transaction ID.
     */
    public GetTransactionRequest withTxid(BigInteger txid) {
        Utils.checkNotNull(txid, "txid");
        this.txid = txid;
        return this;
    }
    
    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        GetTransactionRequest other = (GetTransactionRequest) o;
        return 
            java.util.Objects.deepEquals(this.ledger, other.ledger) &&
            java.util.Objects.deepEquals(this.txid, other.txid);
    }
    
    @Override
    public int hashCode() {
        return java.util.Objects.hash(
            ledger,
            txid);
    }
    
    @Override
    public String toString() {
        return Utils.toString(GetTransactionRequest.class,
                "ledger", ledger,
                "txid", txid);
    }
    
    public final static class Builder {
 
        private String ledger;
 
        private BigInteger txid;  
        
        private Builder() {
          // force use of static builder() method
        }

        /**
         * Name of the ledger.
         */
        public Builder ledger(String ledger) {
            Utils.checkNotNull(ledger, "ledger");
            this.ledger = ledger;
            return this;
        }

        /**
         * Transaction ID.
         */
        public Builder txid(long txid) {
            this.txid = BigInteger.valueOf(txid);
            return this;
        }

        /**
         * Transaction ID.
         */
        public Builder txid(BigInteger txid) {
            Utils.checkNotNull(txid, "txid");
            this.txid = txid;
            return this;
        }
        
        public GetTransactionRequest build() {
            return new GetTransactionRequest(
                ledger,
                txid);
        }
    }
}

