/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.GetWalletSummary;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Exception;

public class GetWalletSummaryRequestBuilder {

    private GetWalletSummaryRequest request;
    private final SDKConfiguration sdkConfiguration;

    public GetWalletSummaryRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public GetWalletSummaryRequestBuilder request(GetWalletSummaryRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public GetWalletSummaryResponse call() throws Exception {
        
        RequestOperation<GetWalletSummaryRequest, GetWalletSummaryResponse> operation
              = new GetWalletSummary.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
