/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.RetryTransferInitiation;
import com.formance.formance_sdk.utils.Headers;
import com.formance.formance_sdk.utils.Utils;
import java.lang.String;
import java.util.Optional;

public class RetryTransferInitiationRequestBuilder {

    private RetryTransferInitiationRequest request;
    private Optional<String> serverURL = Optional.empty();
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public RetryTransferInitiationRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public RetryTransferInitiationRequestBuilder request(RetryTransferInitiationRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }
                
    public RetryTransferInitiationRequestBuilder serverURL(String serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = Optional.of(serverURL);
        return this;
    }

    public RetryTransferInitiationRequestBuilder serverURL(Optional<String> serverURL) {
        Utils.checkNotNull(serverURL, "serverURL");
        this.serverURL = serverURL;
        return this;
    }

    public RetryTransferInitiationResponse call() {
        
        RequestOperation<RetryTransferInitiationRequest, RetryTransferInitiationResponse> operation
              = new RetryTransferInitiation.Sync(sdkConfiguration, serverURL, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
