/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.utils.Utils;

public class RevertTransactionRequestBuilder {

    private RevertTransactionRequest request;
    private final SDKMethodInterfaces.MethodCallRevertTransaction sdk;

    public RevertTransactionRequestBuilder(SDKMethodInterfaces.MethodCallRevertTransaction sdk) {
        this.sdk = sdk;
    }

    public RevertTransactionRequestBuilder request(RevertTransactionRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RevertTransactionResponse call() throws Exception {

        return sdk.revertTransaction(
            request);
    }
}
