/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.RunScript;
import com.formance.formance_sdk.utils.Headers;
import com.formance.formance_sdk.utils.Utils;

public class RunScriptRequestBuilder {

    private RunScriptRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public RunScriptRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public RunScriptRequestBuilder request(RunScriptRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public RunScriptResponse call() {
        
        RequestOperation<RunScriptRequest, RunScriptResponse> operation
              = new RunScript.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
