/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.TestConfig;
import com.formance.formance_sdk.utils.Headers;
import com.formance.formance_sdk.utils.Utils;

public class TestConfigRequestBuilder {

    private TestConfigRequest request;
    private final SDKConfiguration sdkConfiguration;
    private final Headers _headers = new Headers(); 

    public TestConfigRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public TestConfigRequestBuilder request(TestConfigRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public TestConfigResponse call() {
        
        RequestOperation<TestConfigRequest, TestConfigResponse> operation
              = new TestConfig.Sync(sdkConfiguration, _headers);

        return operation.handleResponse(operation.doRequest(request));
    }
}
