/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.utils.Utils;

public class UdpateTransferInitiationStatusRequestBuilder {

    private UdpateTransferInitiationStatusRequest request;
    private final SDKMethodInterfaces.MethodCallUdpateTransferInitiationStatus sdk;

    public UdpateTransferInitiationStatusRequestBuilder(SDKMethodInterfaces.MethodCallUdpateTransferInitiationStatus sdk) {
        this.sdk = sdk;
    }

    public UdpateTransferInitiationStatusRequestBuilder request(UdpateTransferInitiationStatusRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UdpateTransferInitiationStatusResponse call() throws Exception {

        return sdk.udpateTransferInitiationStatus(
            request);
    }
}
