/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.operations.UninstallConnectorV1;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Exception;

public class UninstallConnectorV1RequestBuilder {

    private UninstallConnectorV1Request request;
    private final SDKConfiguration sdkConfiguration;

    public UninstallConnectorV1RequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }

    public UninstallConnectorV1RequestBuilder request(UninstallConnectorV1Request request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public UninstallConnectorV1Response call() throws Exception {
        
        RequestOperation<UninstallConnectorV1Request, UninstallConnectorV1Response> operation
              = new UninstallConnectorV1.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
