/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.models.shared.V2CreateWorkflowRequest;
import com.formance.formance_sdk.utils.Utils;
import java.util.Optional;

public class V2CreateWorkflowRequestBuilder {

    private Optional<? extends V2CreateWorkflowRequest> request = Optional.empty();
    private final SDKMethodInterfaces.MethodCallV2CreateWorkflow sdk;

    public V2CreateWorkflowRequestBuilder(SDKMethodInterfaces.MethodCallV2CreateWorkflow sdk) {
        this.sdk = sdk;
    }
                
    public V2CreateWorkflowRequestBuilder request(V2CreateWorkflowRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V2CreateWorkflowRequestBuilder request(Optional<? extends V2CreateWorkflowRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V2CreateWorkflowResponse call() throws Exception {

        return sdk.createWorkflow(
            request);
    }
}
