/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.operations;

import com.formance.formance_sdk.utils.Utils;

public class V2ListLedgersRequestBuilder {

    private V2ListLedgersRequest request;
    private final SDKMethodInterfaces.MethodCallV2ListLedgers sdk;

    public V2ListLedgersRequestBuilder(SDKMethodInterfaces.MethodCallV2ListLedgers sdk) {
        this.sdk = sdk;
    }

    public V2ListLedgersRequestBuilder request(V2ListLedgersRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V2ListLedgersResponse call() throws Exception {

        return sdk.listLedgers(
            request);
    }
}
