/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import static com.formance.formance_sdk.operations.Operations.RequestOperation;

import com.formance.formance_sdk.SDKConfiguration;
import com.formance.formance_sdk.models.shared.V3CreateAccountRequest;
import com.formance.formance_sdk.operations.V3CreateAccount;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Exception;
import java.util.Optional;

public class V3CreateAccountRequestBuilder {

    private Optional<? extends V3CreateAccountRequest> request = Optional.empty();
    private final SDKConfiguration sdkConfiguration;

    public V3CreateAccountRequestBuilder(SDKConfiguration sdkConfiguration) {
        this.sdkConfiguration = sdkConfiguration;
    }
                
    public V3CreateAccountRequestBuilder request(V3CreateAccountRequest request) {
        Utils.checkNotNull(request, "request");
        this.request = Optional.of(request);
        return this;
    }

    public V3CreateAccountRequestBuilder request(Optional<? extends V3CreateAccountRequest> request) {
        Utils.checkNotNull(request, "request");
        this.request = request;
        return this;
    }

    public V3CreateAccountResponse call() throws Exception {
        
        RequestOperation<Optional<? extends V3CreateAccountRequest>, V3CreateAccountResponse> operation
              = new V3CreateAccount.Sync(sdkConfiguration);

        return operation.handleResponse(operation.doRequest(request));
    }
}
