/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.formance.formance_sdk.models.payments.V3PaymentServiceUserConnectionsCursorResponse;
import com.formance.formance_sdk.utils.Response;
import com.formance.formance_sdk.utils.Utils;
import java.io.InputStream;
import java.lang.Integer;
import java.lang.Override;
import java.lang.String;
import java.lang.SuppressWarnings;
import java.net.http.HttpResponse;
import java.util.Optional;


public class V3ListPaymentServiceUserConnectionsFromConnectorIDResponse implements Response {
    /**
     * HTTP response content type for this operation
     */
    private String contentType;

    /**
     * HTTP response status code for this operation
     */
    private int statusCode;

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    private HttpResponse<InputStream> rawResponse;

    /**
     * OK
     */
    private Optional<? extends V3PaymentServiceUserConnectionsCursorResponse> v3PaymentServiceUserConnectionsCursorResponse;

    @JsonCreator
    public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse,
            Optional<? extends V3PaymentServiceUserConnectionsCursorResponse> v3PaymentServiceUserConnectionsCursorResponse) {
        Utils.checkNotNull(contentType, "contentType");
        Utils.checkNotNull(statusCode, "statusCode");
        Utils.checkNotNull(rawResponse, "rawResponse");
        Utils.checkNotNull(v3PaymentServiceUserConnectionsCursorResponse, "v3PaymentServiceUserConnectionsCursorResponse");
        this.contentType = contentType;
        this.statusCode = statusCode;
        this.rawResponse = rawResponse;
        this.v3PaymentServiceUserConnectionsCursorResponse = v3PaymentServiceUserConnectionsCursorResponse;
    }
    
    public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse(
            String contentType,
            int statusCode,
            HttpResponse<InputStream> rawResponse) {
        this(contentType, statusCode, rawResponse,
            Optional.empty());
    }

    /**
     * HTTP response content type for this operation
     */
    @JsonIgnore
    public String contentType() {
        return contentType;
    }

    /**
     * HTTP response status code for this operation
     */
    @JsonIgnore
    public int statusCode() {
        return statusCode;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    @JsonIgnore
    public HttpResponse<InputStream> rawResponse() {
        return rawResponse;
    }

    /**
     * OK
     */
    @SuppressWarnings("unchecked")
    @JsonIgnore
    public Optional<V3PaymentServiceUserConnectionsCursorResponse> v3PaymentServiceUserConnectionsCursorResponse() {
        return (Optional<V3PaymentServiceUserConnectionsCursorResponse>) v3PaymentServiceUserConnectionsCursorResponse;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * HTTP response content type for this operation
     */
    public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse withContentType(String contentType) {
        Utils.checkNotNull(contentType, "contentType");
        this.contentType = contentType;
        return this;
    }

    /**
     * HTTP response status code for this operation
     */
    public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse withStatusCode(int statusCode) {
        Utils.checkNotNull(statusCode, "statusCode");
        this.statusCode = statusCode;
        return this;
    }

    /**
     * Raw HTTP response; suitable for custom response parsing
     */
    public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse withRawResponse(HttpResponse<InputStream> rawResponse) {
        Utils.checkNotNull(rawResponse, "rawResponse");
        this.rawResponse = rawResponse;
        return this;
    }

    /**
     * OK
     */
    public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse withV3PaymentServiceUserConnectionsCursorResponse(V3PaymentServiceUserConnectionsCursorResponse v3PaymentServiceUserConnectionsCursorResponse) {
        Utils.checkNotNull(v3PaymentServiceUserConnectionsCursorResponse, "v3PaymentServiceUserConnectionsCursorResponse");
        this.v3PaymentServiceUserConnectionsCursorResponse = Optional.ofNullable(v3PaymentServiceUserConnectionsCursorResponse);
        return this;
    }


    /**
     * OK
     */
    public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse withV3PaymentServiceUserConnectionsCursorResponse(Optional<? extends V3PaymentServiceUserConnectionsCursorResponse> v3PaymentServiceUserConnectionsCursorResponse) {
        Utils.checkNotNull(v3PaymentServiceUserConnectionsCursorResponse, "v3PaymentServiceUserConnectionsCursorResponse");
        this.v3PaymentServiceUserConnectionsCursorResponse = v3PaymentServiceUserConnectionsCursorResponse;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3ListPaymentServiceUserConnectionsFromConnectorIDResponse other = (V3ListPaymentServiceUserConnectionsFromConnectorIDResponse) o;
        return 
            Utils.enhancedDeepEquals(this.contentType, other.contentType) &&
            Utils.enhancedDeepEquals(this.statusCode, other.statusCode) &&
            Utils.enhancedDeepEquals(this.rawResponse, other.rawResponse) &&
            Utils.enhancedDeepEquals(this.v3PaymentServiceUserConnectionsCursorResponse, other.v3PaymentServiceUserConnectionsCursorResponse);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            contentType, statusCode, rawResponse,
            v3PaymentServiceUserConnectionsCursorResponse);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3ListPaymentServiceUserConnectionsFromConnectorIDResponse.class,
                "contentType", contentType,
                "statusCode", statusCode,
                "rawResponse", rawResponse,
                "v3PaymentServiceUserConnectionsCursorResponse", v3PaymentServiceUserConnectionsCursorResponse);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String contentType;

        private Integer statusCode;

        private HttpResponse<InputStream> rawResponse;

        private Optional<? extends V3PaymentServiceUserConnectionsCursorResponse> v3PaymentServiceUserConnectionsCursorResponse = Optional.empty();

        private Builder() {
          // force use of static builder() method
        }


        /**
         * HTTP response content type for this operation
         */
        public Builder contentType(String contentType) {
            Utils.checkNotNull(contentType, "contentType");
            this.contentType = contentType;
            return this;
        }


        /**
         * HTTP response status code for this operation
         */
        public Builder statusCode(int statusCode) {
            Utils.checkNotNull(statusCode, "statusCode");
            this.statusCode = statusCode;
            return this;
        }


        /**
         * Raw HTTP response; suitable for custom response parsing
         */
        public Builder rawResponse(HttpResponse<InputStream> rawResponse) {
            Utils.checkNotNull(rawResponse, "rawResponse");
            this.rawResponse = rawResponse;
            return this;
        }


        /**
         * OK
         */
        public Builder v3PaymentServiceUserConnectionsCursorResponse(V3PaymentServiceUserConnectionsCursorResponse v3PaymentServiceUserConnectionsCursorResponse) {
            Utils.checkNotNull(v3PaymentServiceUserConnectionsCursorResponse, "v3PaymentServiceUserConnectionsCursorResponse");
            this.v3PaymentServiceUserConnectionsCursorResponse = Optional.ofNullable(v3PaymentServiceUserConnectionsCursorResponse);
            return this;
        }

        /**
         * OK
         */
        public Builder v3PaymentServiceUserConnectionsCursorResponse(Optional<? extends V3PaymentServiceUserConnectionsCursorResponse> v3PaymentServiceUserConnectionsCursorResponse) {
            Utils.checkNotNull(v3PaymentServiceUserConnectionsCursorResponse, "v3PaymentServiceUserConnectionsCursorResponse");
            this.v3PaymentServiceUserConnectionsCursorResponse = v3PaymentServiceUserConnectionsCursorResponse;
            return this;
        }

        public V3ListPaymentServiceUserConnectionsFromConnectorIDResponse build() {

            return new V3ListPaymentServiceUserConnectionsFromConnectorIDResponse(
                contentType, statusCode, rawResponse,
                v3PaymentServiceUserConnectionsCursorResponse);
        }

    }
}
