/* 
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */
package com.formance.formance_sdk.models.operations;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonIgnore;
import com.formance.formance_sdk.utils.SpeakeasyMetadata;
import com.formance.formance_sdk.utils.Utils;
import java.lang.Override;
import java.lang.String;


public class V3UninstallConnectorRequest {
    /**
     * The connector ID
     */
    @SpeakeasyMetadata("pathParam:style=simple,explode=false,name=connectorID")
    private String connectorID;

    @JsonCreator
    public V3UninstallConnectorRequest(
            String connectorID) {
        Utils.checkNotNull(connectorID, "connectorID");
        this.connectorID = connectorID;
    }

    /**
     * The connector ID
     */
    @JsonIgnore
    public String connectorID() {
        return connectorID;
    }

    public static Builder builder() {
        return new Builder();
    }


    /**
     * The connector ID
     */
    public V3UninstallConnectorRequest withConnectorID(String connectorID) {
        Utils.checkNotNull(connectorID, "connectorID");
        this.connectorID = connectorID;
        return this;
    }

    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        V3UninstallConnectorRequest other = (V3UninstallConnectorRequest) o;
        return 
            Utils.enhancedDeepEquals(this.connectorID, other.connectorID);
    }
    
    @Override
    public int hashCode() {
        return Utils.enhancedHash(
            connectorID);
    }
    
    @Override
    public String toString() {
        return Utils.toString(V3UninstallConnectorRequest.class,
                "connectorID", connectorID);
    }

    @SuppressWarnings("UnusedReturnValue")
    public final static class Builder {

        private String connectorID;

        private Builder() {
          // force use of static builder() method
        }


        /**
         * The connector ID
         */
        public Builder connectorID(String connectorID) {
            Utils.checkNotNull(connectorID, "connectorID");
            this.connectorID = connectorID;
            return this;
        }

        public V3UninstallConnectorRequest build() {

            return new V3UninstallConnectorRequest(
                connectorID);
        }

    }
}
