/* 
 * Code generated by Speakeasy (https://speakeasyapi.dev). DO NOT EDIT.
 */

package com.formance.formance_sdk.models.shared;

import com.fasterxml.jackson.annotation.JsonInclude.Include;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.formance.formance_sdk.utils.DateTimeDeserializer;
import com.formance.formance_sdk.utils.DateTimeSerializer;
import java.time.OffsetDateTime;


public class V2WorkflowInstanceHistoryStage {
    @JsonProperty("attempt")
    public Long attempt;

    public V2WorkflowInstanceHistoryStage withAttempt(Long attempt) {
        this.attempt = attempt;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("error")
    public String error;

    public V2WorkflowInstanceHistoryStage withError(String error) {
        this.error = error;
        return this;
    }
    
    @JsonProperty("input")
    public V2WorkflowInstanceHistoryStageInput input;

    public V2WorkflowInstanceHistoryStage withInput(V2WorkflowInstanceHistoryStageInput input) {
        this.input = input;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("lastFailure")
    public String lastFailure;

    public V2WorkflowInstanceHistoryStage withLastFailure(String lastFailure) {
        this.lastFailure = lastFailure;
        return this;
    }
    
    @JsonProperty("name")
    public String name;

    public V2WorkflowInstanceHistoryStage withName(String name) {
        this.name = name;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("nextExecution")
    public OffsetDateTime nextExecution;

    public V2WorkflowInstanceHistoryStage withNextExecution(OffsetDateTime nextExecution) {
        this.nextExecution = nextExecution;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonProperty("output")
    public V2WorkflowInstanceHistoryStageOutput output;

    public V2WorkflowInstanceHistoryStage withOutput(V2WorkflowInstanceHistoryStageOutput output) {
        this.output = output;
        return this;
    }
    
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("startedAt")
    public OffsetDateTime startedAt;

    public V2WorkflowInstanceHistoryStage withStartedAt(OffsetDateTime startedAt) {
        this.startedAt = startedAt;
        return this;
    }
    
    @JsonProperty("terminated")
    public Boolean terminated;

    public V2WorkflowInstanceHistoryStage withTerminated(Boolean terminated) {
        this.terminated = terminated;
        return this;
    }
    
    @JsonInclude(Include.NON_ABSENT)
    @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("terminatedAt")
    public OffsetDateTime terminatedAt;

    public V2WorkflowInstanceHistoryStage withTerminatedAt(OffsetDateTime terminatedAt) {
        this.terminatedAt = terminatedAt;
        return this;
    }
    
    public V2WorkflowInstanceHistoryStage(@JsonProperty("attempt") Long attempt, @JsonProperty("input") V2WorkflowInstanceHistoryStageInput input, @JsonProperty("name") String name, @JsonProperty("startedAt") OffsetDateTime startedAt, @JsonProperty("terminated") Boolean terminated) {
        this.attempt = attempt;
        this.input = input;
        this.name = name;
        this.startedAt = startedAt;
        this.terminated = terminated;
  }
}
